[workspace]
members = ["crates/core", "crates/editor", "crates/carc", "crates/brsar", "crates/iso"]
resolver = "2"

[workspace.dependencies]
binrw = "0.14"
thiserror = "2"
midly = "0.5"
log = "0.4"
self_update = { version = "0.43", features = ["archive-zip", "compression-zip-deflate", "rustls", "archive-tar", "compression-flate2"] }
discord-rich-presence = "0.2"
indexmap = { version = "2", features = ["std"] }

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
dbg_macro = "deny"
as_underscore = "deny"
fallible_impl_from = "deny"
fn_params_excessive_bools = "deny"
cast_possible_truncation = "allow"
cast_possible_wrap = "allow"
cast_precision_loss = "allow"
cast_sign_loss = "allow"
missing_panics_doc = "allow"
module_name_repetitions = "allow"
