# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WiiMusicPlus.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(829, 598)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 16, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 21, 21))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 16, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 16, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 21, 21))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 16, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 16, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 21, 21))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 32, 32))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setStyleSheet("QToolTip\n"
"{\n"
"     border: 1px solid black;\n"
"     background-color: #ffa02f;\n"
"     padding: 1px;\n"
"     border-radius: 3px;\n"
"     opacity: 100;\n"
"}\n"
"\n"
"QWidget\n"
"{\n"
"    color: white;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QWidget:item:hover\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #ca0619);\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:item:selected\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QMenuBar\n"
"{\n"
"    background: #242424;\n"
"}\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background: transparent;\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    background: #444;\n"
"    border: 1px solid #000;\n"
"    background-color: QLinearGradient(\n"
"        x1:0, y1:0,\n"
"        x2:0, y2:1,\n"
"        stop:1 #212121,\n"
"        stop:0.4 #343434/*,\n"
"        stop:0.2 #343434,\n"
"        stop:0.1 #ffaa00*/\n"
"    );\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"}\n"
"\n"
"QMenu\n"
"{\n"
"    border: 1px solid #000;\n"
"}\n"
"\n"
"QMenu::item\n"
"{\n"
"    padding: 2px 20px 2px 20px;\n"
"}\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:disabled\n"
"{\n"
"    color: #404040;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QSpinBox\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    color: white;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    border-radius: 6;\n"
"    padding: 3px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}\n"
"\n"
"QComboBox\n"
"{\n"
"    selection-background-color: #ffaa00;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox:hover,QPushButton:hover\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"    selection-background-color: #ffaa00;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    border: 2px solid darkgray;\n"
"    selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 15px;\n"
"\n"
"     border-left-width: 0px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"     image: url(:images/images/down_arrow.png);\n"
"}\n"
"\n"
"QGroupBox:focus\n"
"{\n"
"border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QTextEdit:focus\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"     border: 1px solid #222222;\n"
"     background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"     height: 7px;\n"
"     margin: 0px 16px 0 16px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"     subcontrol-position: left;\n"
"     subcontrol-origin: margin;\n"
"}\n"
"\n"
"QAbstractItemView\n"
"{\n"
"    background-color: #121212;\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"      width: 7px;\n"
"      margin: 16px 0 16px 0;\n"
"      border: 1px solid #222222;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      height: 14px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d7801a, stop: 1 #ffa02f);\n"
"      height: 14px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"    padding-left: 1px;\n"
"}\n"
"\n"
"QPlainTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #616161, stop: 0.5 #505050, stop: 0.6 #434343, stop:1 #656565);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"\n"
"QCheckBox:disabled\n"
"{\n"
"color: #414141;\n"
"}\n"
"\n"
"QDockWidget::title\n"
"{\n"
"    text-align: center;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button, QDockWidget::float-button\n"
"{\n"
"    text-align: center;\n"
"    spacing: 1px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button:hover, QDockWidget::float-button:hover\n"
"{\n"
"    background: #242424;\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed, QDockWidget::float-button:pressed\n"
"{\n"
"    padding: 1px -1px -1px 1px;\n"
"}\n"
"\n"
"QMainWindow::separator\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #4c4c4c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QMainWindow::separator:hover\n"
"{\n"
"\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #d7801a, stop:0.5 #b56c17 stop:1 #ffa02f);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QToolBar::handle\n"
"{\n"
"     spacing: 3px; /* spacing between items in the tool bar */\n"
"     background: url(:images/images/handle.png);\n"
"}\n"
"\n"
"QMenu::separator\n"
"{\n"
"    height: 2px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QProgressBar\n"
"{\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #d7801a;\n"
"    width: 2.15px;\n"
"    margin: 0.5px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    color: #b1b1b1;\n"
"    border: 1px solid #444;\n"
"    border-bottom-style: none;\n"
"    background-color: #323232;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    padding-top: 3px;\n"
"    padding-bottom: 2px;\n"
"    margin-right: -1px;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid #444;\n"
"    top: 1px;\n"
"}\n"
"\n"
"QTabBar::tab:last\n"
"{\n"
"    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
"    border-top-right-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:first:!selected\n"
"{\n"
" margin-left: 0px; /* the last selected tab has nothing to overlap with on the right */\n"
"\n"
"\n"
"    border-top-left-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected\n"
"{\n"
"    color: #b1b1b1;\n"
"    border-bottom-style: solid;\n"
"    margin-top: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:.4 #343434);\n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    margin-bottom: 0px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover\n"
"{\n"
"    /*border-top: 2px solid #ffaa00;\n"
"    padding-bottom: 3px;*/\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:0.4 #343434, stop:0.2 #343434, stop:0.1 #ffaa00);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked, QRadioButton::indicator:unchecked{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked\n"
"{\n"
"    background-color: qradialgradient(\n"
"        cx: 0.5, cy: 0.5,\n"
"        fx: 0.5, fy: 0.5,\n"
"        radius: 1.0,\n"
"        stop: 0.25 #ffaa00,\n"
"        stop: 0.3 #323232);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked:disabled\n"
"{\n"
"    background-color: qradialgradient(\n"
"        cx: 0.5, cy: 0.5,\n"
"        fx: 0.5, fy: 0.5,\n"
"        radius: 1.0,\n"
"        stop: 0.25 #323232,\n"
"        stop: 0.3 #323232);\n"
"}\n"
"\n"
"QCheckBox::indicator{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    width: 9px;\n"
"    height: 9px;\n"
"}\n"
"\n"
"QRadioButton::indicator\n"
"{\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover, QCheckBox::indicator:hover\n"
"{\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image:url(:images/images/checkbox.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled, QRadioButton::indicator:disabled\n"
"{\n"
"    border: 1px solid #444;\n"
"}")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.centralwidget.setPalette(palette)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.MainWidget = QtWidgets.QStackedWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Continuum Bold")
        font.setPointSize(72)
        self.MainWidget.setFont(font)
        self.MainWidget.setObjectName("MainWidget")
        self.MainPage = QtWidgets.QWidget()
        self.MainPage.setObjectName("MainPage")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.MainPage)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.MP_Title = QtWidgets.QLabel(self.MainPage)
        self.MP_Title.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(26)
        self.MP_Title.setFont(font)
        self.MP_Title.setScaledContents(False)
        self.MP_Title.setObjectName("MP_Title")
        self.verticalLayout_9.addWidget(self.MP_Title)
        self.MP_vLine = QtWidgets.QFrame(self.MainPage)
        self.MP_vLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.MP_vLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MP_vLine.setObjectName("MP_vLine")
        self.verticalLayout_9.addWidget(self.MP_vLine)
        self.MP_LoadedFile_Label = QtWidgets.QLabel(self.MainPage)
        self.MP_LoadedFile_Label.setObjectName("MP_LoadedFile_Label")
        self.verticalLayout_9.addWidget(self.MP_LoadedFile_Label)
        self.MP_LoadedFile_Path = QtWidgets.QLabel(self.MainPage)
        self.MP_LoadedFile_Path.setMaximumSize(QtCore.QSize(16777215, 26))
        self.MP_LoadedFile_Path.setStyleSheet("QLabel\n"
"{\n"
"padding: 1px;\n"
"border: 1px solid;\n"
"border-color: #1e1e1e;\n"
"background-color: #242424;\n"
"padding-top: 6px;\n"
"padding-bottom: 6px;\n"
"}")
        self.MP_LoadedFile_Path.setObjectName("MP_LoadedFile_Path")
        self.verticalLayout_9.addWidget(self.MP_LoadedFile_Path)
        self.MP_MainFeatures = QtWidgets.QHBoxLayout()
        self.MP_MainFeatures.setObjectName("MP_MainFeatures")
        self.MP_SongEditor_Button = QtWidgets.QPushButton(self.MainPage)
        self.MP_SongEditor_Button.setMinimumSize(QtCore.QSize(0, 64))
        font = QtGui.QFont()
        font.setFamily("Continuum Bold")
        font.setPointSize(26)
        self.MP_SongEditor_Button.setFont(font)
        self.MP_SongEditor_Button.setObjectName("MP_SongEditor_Button")
        self.MP_MainFeatures.addWidget(self.MP_SongEditor_Button)
        self.MP_StyleEditor_Button = QtWidgets.QPushButton(self.MainPage)
        self.MP_StyleEditor_Button.setMinimumSize(QtCore.QSize(0, 64))
        font = QtGui.QFont()
        font.setFamily("Continuum Bold")
        font.setPointSize(26)
        self.MP_StyleEditor_Button.setFont(font)
        self.MP_StyleEditor_Button.setObjectName("MP_StyleEditor_Button")
        self.MP_MainFeatures.addWidget(self.MP_StyleEditor_Button)
        self.verticalLayout_9.addLayout(self.MP_MainFeatures)
        self.line = QtWidgets.QFrame(self.MainPage)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_9.addWidget(self.line)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.MP_Advanced = QtWidgets.QGroupBox(self.MainPage)
        self.MP_Advanced.setObjectName("MP_Advanced")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.MP_Advanced)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.MP_Advanced1 = QtWidgets.QHBoxLayout()
        self.MP_Advanced1.setObjectName("MP_Advanced1")
        self.MP_EditText_Button = QtWidgets.QPushButton(self.MP_Advanced)
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(14)
        self.MP_EditText_Button.setFont(font)
        self.MP_EditText_Button.setObjectName("MP_EditText_Button")
        self.MP_Advanced1.addWidget(self.MP_EditText_Button)
        self.MP_DefaultStyle_Button = QtWidgets.QPushButton(self.MP_Advanced)
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(14)
        self.MP_DefaultStyle_Button.setFont(font)
        self.MP_DefaultStyle_Button.setObjectName("MP_DefaultStyle_Button")
        self.MP_Advanced1.addWidget(self.MP_DefaultStyle_Button)
        self.MP_ReplaceSound_Button = QtWidgets.QPushButton(self.MP_Advanced)
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(14)
        self.MP_ReplaceSound_Button.setFont(font)
        self.MP_ReplaceSound_Button.setObjectName("MP_ReplaceSound_Button")
        self.MP_Advanced1.addWidget(self.MP_ReplaceSound_Button)
        self.MP_RemoveSong_Button = QtWidgets.QPushButton(self.MP_Advanced)
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(14)
        self.MP_RemoveSong_Button.setFont(font)
        self.MP_RemoveSong_Button.setObjectName("MP_RemoveSong_Button")
        self.MP_Advanced1.addWidget(self.MP_RemoveSong_Button)
        self.verticalLayout_11.addLayout(self.MP_Advanced1)
        self.MP_Advanced2 = QtWidgets.QHBoxLayout()
        self.MP_Advanced2.setObjectName("MP_Advanced2")
        self.MP_GeckocodeConvert_Button = QtWidgets.QPushButton(self.MP_Advanced)
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(14)
        self.MP_GeckocodeConvert_Button.setFont(font)
        self.MP_GeckocodeConvert_Button.setObjectName("MP_GeckocodeConvert_Button")
        self.MP_Advanced2.addWidget(self.MP_GeckocodeConvert_Button)
        self.MP_MainDolPatch_Button = QtWidgets.QPushButton(self.MP_Advanced)
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(14)
        self.MP_MainDolPatch_Button.setFont(font)
        self.MP_MainDolPatch_Button.setObjectName("MP_MainDolPatch_Button")
        self.MP_Advanced2.addWidget(self.MP_MainDolPatch_Button)
        self.MP_Riivolution_Button = QtWidgets.QPushButton(self.MP_Advanced)
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(14)
        self.MP_Riivolution_Button.setFont(font)
        self.MP_Riivolution_Button.setObjectName("MP_Riivolution_Button")
        self.MP_Advanced2.addWidget(self.MP_Riivolution_Button)
        self.verticalLayout_11.addLayout(self.MP_Advanced2)
        self.verticalLayout_9.addWidget(self.MP_Advanced)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem1)
        self.MP_RomEditing = QtWidgets.QGroupBox(self.MainPage)
        self.MP_RomEditing.setObjectName("MP_RomEditing")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.MP_RomEditing)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.MP_RomEditing1 = QtWidgets.QHBoxLayout()
        self.MP_RomEditing1.setObjectName("MP_RomEditing1")
        self.MP_RevertChanges_Button = QtWidgets.QPushButton(self.MP_RomEditing)
        self.MP_RevertChanges_Button.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(14)
        self.MP_RevertChanges_Button.setFont(font)
        self.MP_RevertChanges_Button.setObjectName("MP_RevertChanges_Button")
        self.MP_RomEditing1.addWidget(self.MP_RevertChanges_Button)
        self.MP_PackRom_Button = QtWidgets.QPushButton(self.MP_RomEditing)
        self.MP_PackRom_Button.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(14)
        self.MP_PackRom_Button.setFont(font)
        self.MP_PackRom_Button.setObjectName("MP_PackRom_Button")
        self.MP_RomEditing1.addWidget(self.MP_PackRom_Button)
        self.verticalLayout_18.addLayout(self.MP_RomEditing1)
        self.MP_RomEditing2 = QtWidgets.QHBoxLayout()
        self.MP_RomEditing2.setObjectName("MP_RomEditing2")
        self.MP_ImportFiles_Button = QtWidgets.QPushButton(self.MP_RomEditing)
        self.MP_ImportFiles_Button.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(14)
        self.MP_ImportFiles_Button.setFont(font)
        self.MP_ImportFiles_Button.setObjectName("MP_ImportFiles_Button")
        self.MP_RomEditing2.addWidget(self.MP_ImportFiles_Button)
        self.MP_ExportFiles_Button = QtWidgets.QPushButton(self.MP_RomEditing)
        self.MP_ExportFiles_Button.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(14)
        self.MP_ExportFiles_Button.setFont(font)
        self.MP_ExportFiles_Button.setObjectName("MP_ExportFiles_Button")
        self.MP_RomEditing2.addWidget(self.MP_ExportFiles_Button)
        self.MP_ImportChanges_Button = QtWidgets.QPushButton(self.MP_RomEditing)
        self.MP_ImportChanges_Button.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(14)
        self.MP_ImportChanges_Button.setFont(font)
        self.MP_ImportChanges_Button.setObjectName("MP_ImportChanges_Button")
        self.MP_RomEditing2.addWidget(self.MP_ImportChanges_Button)
        self.verticalLayout_18.addLayout(self.MP_RomEditing2)
        self.verticalLayout_9.addWidget(self.MP_RomEditing)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem2)
        self.MainWidget.addWidget(self.MainPage)
        self.SongEditor = QtWidgets.QWidget()
        self.SongEditor.setObjectName("SongEditor")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.SongEditor)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Title = QtWidgets.QHBoxLayout()
        self.Title.setObjectName("Title")
        self.SE_Title = QtWidgets.QLabel(self.SongEditor)
        self.SE_Title.setMaximumSize(QtCore.QSize(16777215, 44))
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(26)
        self.SE_Title.setFont(font)
        self.SE_Title.setObjectName("SE_Title")
        self.Title.addWidget(self.SE_Title)
        self.SE_Back_Button = QtWidgets.QPushButton(self.SongEditor)
        self.SE_Back_Button.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SE_Back_Button.setFont(font)
        self.SE_Back_Button.setObjectName("SE_Back_Button")
        self.Title.addWidget(self.SE_Back_Button)
        self.verticalLayout_2.addLayout(self.Title)
        self.SE_MainLayout = QtWidgets.QHBoxLayout()
        self.SE_MainLayout.setObjectName("SE_MainLayout")
        self.SE_MidiAndText = QtWidgets.QVBoxLayout()
        self.SE_MidiAndText.setObjectName("SE_MidiAndText")
        self.SE_Midi = QtWidgets.QGroupBox(self.SongEditor)
        self.SE_Midi.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SE_Midi.sizePolicy().hasHeightForWidth())
        self.SE_Midi.setSizePolicy(sizePolicy)
        self.SE_Midi.setFocusPolicy(QtCore.Qt.NoFocus)
        self.SE_Midi.setCheckable(True)
        self.SE_Midi.setObjectName("SE_Midi")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.SE_Midi)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.SE_Midi_File_Score_Label = QtWidgets.QLabel(self.SE_Midi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SE_Midi_File_Score_Label.sizePolicy().hasHeightForWidth())
        self.SE_Midi_File_Score_Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SE_Midi_File_Score_Label.setFont(font)
        self.SE_Midi_File_Score_Label.setAcceptDrops(True)
        self.SE_Midi_File_Score_Label.setStyleSheet("QLabel\n"
"{\n"
"padding: 1px;\n"
"border: 1px solid;\n"
"border-color: #1e1e1e;\n"
"background-color: #242424;\n"
"padding-top: 6px;\n"
"padding-bottom: 6px;\n"
"}")
        self.SE_Midi_File_Score_Label.setObjectName("SE_Midi_File_Score_Label")
        self.gridLayout.addWidget(self.SE_Midi_File_Score_Label, 0, 1, 1, 1)
        self.SE_Midi_File_Score_Button = QtWidgets.QPushButton(self.SE_Midi)
        self.SE_Midi_File_Score_Button.setMinimumSize(QtCore.QSize(100, 0))
        self.SE_Midi_File_Score_Button.setObjectName("SE_Midi_File_Score_Button")
        self.gridLayout.addWidget(self.SE_Midi_File_Score_Button, 0, 2, 1, 1)
        self.SE_Midi_File_Score_Title = QtWidgets.QLabel(self.SE_Midi)
        self.SE_Midi_File_Score_Title.setObjectName("SE_Midi_File_Score_Title")
        self.gridLayout.addWidget(self.SE_Midi_File_Score_Title, 0, 0, 1, 1)
        self.SE_Midi_File_Song_Label = QtWidgets.QLabel(self.SE_Midi)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SE_Midi_File_Song_Label.sizePolicy().hasHeightForWidth())
        self.SE_Midi_File_Song_Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SE_Midi_File_Song_Label.setFont(font)
        self.SE_Midi_File_Song_Label.setAcceptDrops(True)
        self.SE_Midi_File_Song_Label.setStyleSheet("QLabel\n"
"{\n"
"padding: 1px;\n"
"border: 1px solid;\n"
"border-color: #1e1e1e;\n"
"background-color: #242424;\n"
"padding-top: 6px;\n"
"padding-bottom: 6px;\n"
"}")
        self.SE_Midi_File_Song_Label.setObjectName("SE_Midi_File_Song_Label")
        self.gridLayout.addWidget(self.SE_Midi_File_Song_Label, 1, 1, 1, 1)
        self.SE_Midi_File_Song_Title = QtWidgets.QLabel(self.SE_Midi)
        self.SE_Midi_File_Song_Title.setObjectName("SE_Midi_File_Song_Title")
        self.gridLayout.addWidget(self.SE_Midi_File_Song_Title, 1, 0, 1, 1)
        self.SE_Midi_File_Song_Button = QtWidgets.QPushButton(self.SE_Midi)
        self.SE_Midi_File_Song_Button.setMinimumSize(QtCore.QSize(100, 0))
        self.SE_Midi_File_Song_Button.setObjectName("SE_Midi_File_Song_Button")
        self.gridLayout.addWidget(self.SE_Midi_File_Song_Button, 1, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.SE_Midi_File_Replace_Song = QtWidgets.QCheckBox(self.SE_Midi)
        self.SE_Midi_File_Replace_Song.setEnabled(True)
        self.SE_Midi_File_Replace_Song.setChecked(True)
        self.SE_Midi_File_Replace_Song.setObjectName("SE_Midi_File_Replace_Song")
        self.verticalLayout_4.addWidget(self.SE_Midi_File_Replace_Song)
        self.SE_Midi_hLine = QtWidgets.QFrame(self.SE_Midi)
        self.SE_Midi_hLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.SE_Midi_hLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.SE_Midi_hLine.setObjectName("SE_Midi_hLine")
        self.verticalLayout_4.addWidget(self.SE_Midi_hLine)
        self.SE_Midi_Info = QtWidgets.QHBoxLayout()
        self.SE_Midi_Info.setObjectName("SE_Midi_Info")
        self.SE_Midi_Tempo = QtWidgets.QFrame(self.SE_Midi)
        self.SE_Midi_Tempo.setObjectName("SE_Midi_Tempo")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.SE_Midi_Tempo)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SE_Midi_Tempo_Label = QtWidgets.QLabel(self.SE_Midi_Tempo)
        self.SE_Midi_Tempo_Label.setObjectName("SE_Midi_Tempo_Label")
        self.verticalLayout.addWidget(self.SE_Midi_Tempo_Label)
        self.SE_Midi_Tempo_Layout = QtWidgets.QHBoxLayout()
        self.SE_Midi_Tempo_Layout.setObjectName("SE_Midi_Tempo_Layout")
        self.SE_Midi_Tempo_Input = QtWidgets.QSpinBox(self.SE_Midi_Tempo)
        self.SE_Midi_Tempo_Input.setMinimumSize(QtCore.QSize(80, 0))
        self.SE_Midi_Tempo_Input.setMaximum(10000)
        self.SE_Midi_Tempo_Input.setObjectName("SE_Midi_Tempo_Input")
        self.SE_Midi_Tempo_Layout.addWidget(self.SE_Midi_Tempo_Input)
        self.SE_Midi_Tempo_BPM = QtWidgets.QLabel(self.SE_Midi_Tempo)
        self.SE_Midi_Tempo_BPM.setMaximumSize(QtCore.QSize(30, 16777215))
        self.SE_Midi_Tempo_BPM.setObjectName("SE_Midi_Tempo_BPM")
        self.SE_Midi_Tempo_Layout.addWidget(self.SE_Midi_Tempo_BPM)
        self.verticalLayout.addLayout(self.SE_Midi_Tempo_Layout)
        self.SE_Midi_Info.addWidget(self.SE_Midi_Tempo)
        self.SE_Midi_vLine_1 = QtWidgets.QFrame(self.SE_Midi)
        self.SE_Midi_vLine_1.setFrameShape(QtWidgets.QFrame.VLine)
        self.SE_Midi_vLine_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.SE_Midi_vLine_1.setObjectName("SE_Midi_vLine_1")
        self.SE_Midi_Info.addWidget(self.SE_Midi_vLine_1)
        self.SE_Midi_Length = QtWidgets.QFrame(self.SE_Midi)
        self.SE_Midi_Length.setObjectName("SE_Midi_Length")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.SE_Midi_Length)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.SE_Midi_Length_Label = QtWidgets.QLabel(self.SE_Midi_Length)
        self.SE_Midi_Length_Label.setObjectName("SE_Midi_Length_Label")
        self.verticalLayout_8.addWidget(self.SE_Midi_Length_Label)
        self.SE_Midi_Length_Layout = QtWidgets.QHBoxLayout()
        self.SE_Midi_Length_Layout.setObjectName("SE_Midi_Length_Layout")
        self.SE_Midi_Length_Input = QtWidgets.QSpinBox(self.SE_Midi_Length)
        self.SE_Midi_Length_Input.setMinimumSize(QtCore.QSize(80, 0))
        self.SE_Midi_Length_Input.setMaximum(10000)
        self.SE_Midi_Length_Input.setProperty("value", 0)
        self.SE_Midi_Length_Input.setObjectName("SE_Midi_Length_Input")
        self.SE_Midi_Length_Layout.addWidget(self.SE_Midi_Length_Input)
        self.SE_Midi_Length_Measures = QtWidgets.QRadioButton(self.SE_Midi_Length)
        self.SE_Midi_Length_Measures.setFocusPolicy(QtCore.Qt.TabFocus)
        self.SE_Midi_Length_Measures.setChecked(True)
        self.SE_Midi_Length_Measures.setObjectName("SE_Midi_Length_Measures")
        self.SE_Midi_Length_Layout.addWidget(self.SE_Midi_Length_Measures)
        self.SE_Midi_Length_Beats = QtWidgets.QRadioButton(self.SE_Midi_Length)
        self.SE_Midi_Length_Beats.setFocusPolicy(QtCore.Qt.TabFocus)
        self.SE_Midi_Length_Beats.setChecked(False)
        self.SE_Midi_Length_Beats.setObjectName("SE_Midi_Length_Beats")
        self.SE_Midi_Length_Layout.addWidget(self.SE_Midi_Length_Beats)
        self.verticalLayout_8.addLayout(self.SE_Midi_Length_Layout)
        self.SE_Midi_Info.addWidget(self.SE_Midi_Length)
        self.SE_Midi_vLine_2 = QtWidgets.QFrame(self.SE_Midi)
        self.SE_Midi_vLine_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.SE_Midi_vLine_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.SE_Midi_vLine_2.setObjectName("SE_Midi_vLine_2")
        self.SE_Midi_Info.addWidget(self.SE_Midi_vLine_2)
        self.SE_Midi_TimeSignature = QtWidgets.QFrame(self.SE_Midi)
        self.SE_Midi_TimeSignature.setMaximumSize(QtCore.QSize(106, 16777215))
        self.SE_Midi_TimeSignature.setObjectName("SE_Midi_TimeSignature")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.SE_Midi_TimeSignature)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.SE_Midi_TimeSignature_Label = QtWidgets.QLabel(self.SE_Midi_TimeSignature)
        self.SE_Midi_TimeSignature_Label.setObjectName("SE_Midi_TimeSignature_Label")
        self.verticalLayout_6.addWidget(self.SE_Midi_TimeSignature_Label, 0, QtCore.Qt.AlignTop)
        self.SE_Midi_TimeSignature_Layout = QtWidgets.QHBoxLayout()
        self.SE_Midi_TimeSignature_Layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.SE_Midi_TimeSignature_Layout.setObjectName("SE_Midi_TimeSignature_Layout")
        self.SE_Midi_TimeSignature_4 = QtWidgets.QRadioButton(self.SE_Midi_TimeSignature)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SE_Midi_TimeSignature_4.sizePolicy().hasHeightForWidth())
        self.SE_Midi_TimeSignature_4.setSizePolicy(sizePolicy)
        self.SE_Midi_TimeSignature_4.setMinimumSize(QtCore.QSize(50, 0))
        self.SE_Midi_TimeSignature_4.setMouseTracking(True)
        self.SE_Midi_TimeSignature_4.setFocusPolicy(QtCore.Qt.TabFocus)
        self.SE_Midi_TimeSignature_4.setChecked(True)
        self.SE_Midi_TimeSignature_4.setObjectName("SE_Midi_TimeSignature_4")
        self.SE_Midi_TimeSignature_Layout.addWidget(self.SE_Midi_TimeSignature_4)
        self.SE_Midi_TimeSignature_3 = QtWidgets.QRadioButton(self.SE_Midi_TimeSignature)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SE_Midi_TimeSignature_3.sizePolicy().hasHeightForWidth())
        self.SE_Midi_TimeSignature_3.setSizePolicy(sizePolicy)
        self.SE_Midi_TimeSignature_3.setMinimumSize(QtCore.QSize(50, 0))
        self.SE_Midi_TimeSignature_3.setFocusPolicy(QtCore.Qt.TabFocus)
        self.SE_Midi_TimeSignature_3.setObjectName("SE_Midi_TimeSignature_3")
        self.SE_Midi_TimeSignature_Layout.addWidget(self.SE_Midi_TimeSignature_3)
        self.verticalLayout_6.addLayout(self.SE_Midi_TimeSignature_Layout)
        self.SE_Midi_Info.addWidget(self.SE_Midi_TimeSignature)
        self.verticalLayout_4.addLayout(self.SE_Midi_Info)
        self.SE_MidiAndText.addWidget(self.SE_Midi)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.SE_MidiAndText.addItem(spacerItem3)
        self.SE_ChangeSongText = QtWidgets.QGroupBox(self.SongEditor)
        self.SE_ChangeSongText.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SE_ChangeSongText.sizePolicy().hasHeightForWidth())
        self.SE_ChangeSongText.setSizePolicy(sizePolicy)
        self.SE_ChangeSongText.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.SE_ChangeSongText.setCheckable(False)
        self.SE_ChangeSongText.setChecked(False)
        self.SE_ChangeSongText.setObjectName("SE_ChangeSongText")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.SE_ChangeSongText)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.SE_ChangeSongText_NameAndGenre = QtWidgets.QHBoxLayout()
        self.SE_ChangeSongText_NameAndGenre.setObjectName("SE_ChangeSongText_NameAndGenre")
        self.SE_ChangeSongText_Name = QtWidgets.QVBoxLayout()
        self.SE_ChangeSongText_Name.setObjectName("SE_ChangeSongText_Name")
        self.SE_ChangeSongText_Name_Label = QtWidgets.QLabel(self.SE_ChangeSongText)
        self.SE_ChangeSongText_Name_Label.setMaximumSize(QtCore.QSize(16777215, 13))
        self.SE_ChangeSongText_Name_Label.setObjectName("SE_ChangeSongText_Name_Label")
        self.SE_ChangeSongText_Name.addWidget(self.SE_ChangeSongText_Name_Label)
        self.SE_ChangeSongText_Name_Input = QtWidgets.QLineEdit(self.SE_ChangeSongText)
        self.SE_ChangeSongText_Name_Input.setMaximumSize(QtCore.QSize(16777215, 20))
        self.SE_ChangeSongText_Name_Input.setText("")
        self.SE_ChangeSongText_Name_Input.setObjectName("SE_ChangeSongText_Name_Input")
        self.SE_ChangeSongText_Name.addWidget(self.SE_ChangeSongText_Name_Input)
        self.SE_ChangeSongText_NameAndGenre.addLayout(self.SE_ChangeSongText_Name)
        self.SE_ChangeSongText_vLine = QtWidgets.QFrame(self.SE_ChangeSongText)
        self.SE_ChangeSongText_vLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.SE_ChangeSongText_vLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.SE_ChangeSongText_vLine.setObjectName("SE_ChangeSongText_vLine")
        self.SE_ChangeSongText_NameAndGenre.addWidget(self.SE_ChangeSongText_vLine)
        self.SE_ChangeSongText_Genre = QtWidgets.QVBoxLayout()
        self.SE_ChangeSongText_Genre.setObjectName("SE_ChangeSongText_Genre")
        self.SE_ChangeSongText_Genre_Label = QtWidgets.QLabel(self.SE_ChangeSongText)
        self.SE_ChangeSongText_Genre_Label.setMaximumSize(QtCore.QSize(16777215, 13))
        self.SE_ChangeSongText_Genre_Label.setObjectName("SE_ChangeSongText_Genre_Label")
        self.SE_ChangeSongText_Genre.addWidget(self.SE_ChangeSongText_Genre_Label)
        self.SE_ChangeSongText_Genre_Input = QtWidgets.QLineEdit(self.SE_ChangeSongText)
        self.SE_ChangeSongText_Genre_Input.setText("")
        self.SE_ChangeSongText_Genre_Input.setObjectName("SE_ChangeSongText_Genre_Input")
        self.SE_ChangeSongText_Genre.addWidget(self.SE_ChangeSongText_Genre_Input)
        self.SE_ChangeSongText_NameAndGenre.addLayout(self.SE_ChangeSongText_Genre)
        self.verticalLayout_5.addLayout(self.SE_ChangeSongText_NameAndGenre)
        self.SE_ChangeSongText_hLine = QtWidgets.QFrame(self.SE_ChangeSongText)
        self.SE_ChangeSongText_hLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.SE_ChangeSongText_hLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.SE_ChangeSongText_hLine.setObjectName("SE_ChangeSongText_hLine")
        self.verticalLayout_5.addWidget(self.SE_ChangeSongText_hLine)
        self.SE_ChangeSongText_Desc_Label = QtWidgets.QLabel(self.SE_ChangeSongText)
        self.SE_ChangeSongText_Desc_Label.setObjectName("SE_ChangeSongText_Desc_Label")
        self.verticalLayout_5.addWidget(self.SE_ChangeSongText_Desc_Label)
        self.SE_ChangeSongText_Desc_Input = QtWidgets.QTextEdit(self.SE_ChangeSongText)
        self.SE_ChangeSongText_Desc_Input.setMinimumSize(QtCore.QSize(0, 70))
        self.SE_ChangeSongText_Desc_Input.setMaximumSize(QtCore.QSize(16777215, 71))
        self.SE_ChangeSongText_Desc_Input.setAcceptDrops(False)
        self.SE_ChangeSongText_Desc_Input.setObjectName("SE_ChangeSongText_Desc_Input")
        self.verticalLayout_5.addWidget(self.SE_ChangeSongText_Desc_Input)
        self.SE_MidiAndText.addWidget(self.SE_ChangeSongText)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.SE_MidiAndText.addItem(spacerItem4)
        self.SE_Patch = QtWidgets.QPushButton(self.SongEditor)
        self.SE_Patch.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(20)
        self.SE_Patch.setFont(font)
        self.SE_Patch.setObjectName("SE_Patch")
        self.SE_MidiAndText.addWidget(self.SE_Patch)
        self.SE_MainLayout.addLayout(self.SE_MidiAndText)
        self.SE_SongToChangeBox = QtWidgets.QGroupBox(self.SongEditor)
        self.SE_SongToChangeBox.setMinimumSize(QtCore.QSize(0, 0))
        self.SE_SongToChangeBox.setObjectName("SE_SongToChangeBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.SE_SongToChangeBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SE_SongToChange = QtWidgets.QListWidget(self.SE_SongToChangeBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SE_SongToChange.sizePolicy().hasHeightForWidth())
        self.SE_SongToChange.setSizePolicy(sizePolicy)
        self.SE_SongToChange.setObjectName("SE_SongToChange")
        self.verticalLayout_3.addWidget(self.SE_SongToChange)
        self.SE_Style = QtWidgets.QHBoxLayout()
        self.SE_Style.setObjectName("SE_Style")
        self.SE_StyleLabel = QtWidgets.QLabel(self.SE_SongToChangeBox)
        self.SE_StyleLabel.setObjectName("SE_StyleLabel")
        self.SE_Style.addWidget(self.SE_StyleLabel)
        self.SE_StyleText = QtWidgets.QLabel(self.SE_SongToChangeBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SE_StyleText.sizePolicy().hasHeightForWidth())
        self.SE_StyleText.setSizePolicy(sizePolicy)
        self.SE_StyleText.setMinimumSize(QtCore.QSize(0, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SE_StyleText.setFont(font)
        self.SE_StyleText.setAcceptDrops(True)
        self.SE_StyleText.setStyleSheet("QLabel\n"
"{\n"
"padding: 1px;\n"
"border: 1px solid;\n"
"border-color: #1e1e1e;\n"
"background-color: #242424;\n"
"padding-top: 6px;\n"
"padding-bottom: 6px;\n"
"}")
        self.SE_StyleText.setText("")
        self.SE_StyleText.setObjectName("SE_StyleText")
        self.SE_Style.addWidget(self.SE_StyleText)
        self.verticalLayout_3.addLayout(self.SE_Style)
        self.SE_StyleButtons = QtWidgets.QHBoxLayout()
        self.SE_StyleButtons.setObjectName("SE_StyleButtons")
        self.SE_OpenStyleEditor = QtWidgets.QPushButton(self.SE_SongToChangeBox)
        self.SE_OpenStyleEditor.setObjectName("SE_OpenStyleEditor")
        self.SE_StyleButtons.addWidget(self.SE_OpenStyleEditor)
        self.SE_OpenDefaultStyleEditor = QtWidgets.QPushButton(self.SE_SongToChangeBox)
        self.SE_OpenDefaultStyleEditor.setObjectName("SE_OpenDefaultStyleEditor")
        self.SE_StyleButtons.addWidget(self.SE_OpenDefaultStyleEditor)
        self.verticalLayout_3.addLayout(self.SE_StyleButtons)
        self.SE_MainLayout.addWidget(self.SE_SongToChangeBox)
        self.verticalLayout_2.addLayout(self.SE_MainLayout)
        self.MainWidget.addWidget(self.SongEditor)
        self.StyleEditor = QtWidgets.QWidget()
        self.StyleEditor.setObjectName("StyleEditor")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.StyleEditor)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.StE_Title = QtWidgets.QHBoxLayout()
        self.StE_Title.setObjectName("StE_Title")
        self.StE_Title_Label = QtWidgets.QLabel(self.StyleEditor)
        self.StE_Title_Label.setMaximumSize(QtCore.QSize(16777215, 44))
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(26)
        self.StE_Title_Label.setFont(font)
        self.StE_Title_Label.setObjectName("StE_Title_Label")
        self.StE_Title.addWidget(self.StE_Title_Label)
        self.StE_Back_Button = QtWidgets.QPushButton(self.StyleEditor)
        self.StE_Back_Button.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.StE_Back_Button.setFont(font)
        self.StE_Back_Button.setObjectName("StE_Back_Button")
        self.StE_Title.addWidget(self.StE_Back_Button)
        self.verticalLayout_10.addLayout(self.StE_Title)
        self.StE_MainLayout = QtWidgets.QHBoxLayout()
        self.StE_MainLayout.setObjectName("StE_MainLayout")
        self.StE_PartsAndFile = QtWidgets.QVBoxLayout()
        self.StE_PartsAndFile.setObjectName("StE_PartsAndFile")
        self.StE_Parts = QtWidgets.QGroupBox(self.StyleEditor)
        self.StE_Parts.setMinimumSize(QtCore.QSize(200, 0))
        self.StE_Parts.setMaximumSize(QtCore.QSize(16777215, 300))
        self.StE_Parts.setFocusPolicy(QtCore.Qt.NoFocus)
        self.StE_Parts.setCheckable(False)
        self.StE_Parts.setObjectName("StE_Parts")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.StE_Parts)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.StE_Parts_List = QtWidgets.QGridLayout()
        self.StE_Parts_List.setObjectName("StE_Parts_List")
        self.StE_Part_Percussion1_Instrument = QtWidgets.QLabel(self.StE_Parts)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.StE_Part_Percussion1_Instrument.setFont(font)
        self.StE_Part_Percussion1_Instrument.setAcceptDrops(True)
        self.StE_Part_Percussion1_Instrument.setStyleSheet("padding: 1px;\n"
"border: 1px solid;\n"
"border-color: #1e1e1e;\n"
"background-color: #242424;")
        self.StE_Part_Percussion1_Instrument.setText("")
        self.StE_Part_Percussion1_Instrument.setObjectName("StE_Part_Percussion1_Instrument")
        self.StE_Parts_List.addWidget(self.StE_Part_Percussion1_Instrument, 4, 1, 1, 1)
        self.StE_Part_Bass_Label = QtWidgets.QLabel(self.StE_Parts)
        self.StE_Part_Bass_Label.setObjectName("StE_Part_Bass_Label")
        self.StE_Parts_List.addWidget(self.StE_Part_Bass_Label, 3, 0, 1, 1)
        self.StE_Part_Percussion1_Label = QtWidgets.QLabel(self.StE_Parts)
        self.StE_Part_Percussion1_Label.setObjectName("StE_Part_Percussion1_Label")
        self.StE_Parts_List.addWidget(self.StE_Part_Percussion1_Label, 4, 0, 1, 1)
        self.StE_Part_Harmony_Label = QtWidgets.QLabel(self.StE_Parts)
        self.StE_Part_Harmony_Label.setObjectName("StE_Part_Harmony_Label")
        self.StE_Parts_List.addWidget(self.StE_Part_Harmony_Label, 1, 0, 1, 1)
        self.StE_Part_Bass_Instrument = QtWidgets.QLabel(self.StE_Parts)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.StE_Part_Bass_Instrument.setFont(font)
        self.StE_Part_Bass_Instrument.setAcceptDrops(True)
        self.StE_Part_Bass_Instrument.setStyleSheet("padding: 1px;\n"
"border: 1px solid;\n"
"border-color: #1e1e1e;\n"
"background-color: #242424;")
        self.StE_Part_Bass_Instrument.setText("")
        self.StE_Part_Bass_Instrument.setObjectName("StE_Part_Bass_Instrument")
        self.StE_Parts_List.addWidget(self.StE_Part_Bass_Instrument, 3, 1, 1, 1)
        self.StE_Part_Chords_Instrument = QtWidgets.QLabel(self.StE_Parts)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.StE_Part_Chords_Instrument.setFont(font)
        self.StE_Part_Chords_Instrument.setAcceptDrops(True)
        self.StE_Part_Chords_Instrument.setStyleSheet("padding: 1px;\n"
"border: 1px solid;\n"
"border-color: #1e1e1e;\n"
"background-color: #242424;")
        self.StE_Part_Chords_Instrument.setText("")
        self.StE_Part_Chords_Instrument.setObjectName("StE_Part_Chords_Instrument")
        self.StE_Parts_List.addWidget(self.StE_Part_Chords_Instrument, 2, 1, 1, 1)
        self.StE_Part_Harmony_Instrument = QtWidgets.QLabel(self.StE_Parts)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.StE_Part_Harmony_Instrument.setFont(font)
        self.StE_Part_Harmony_Instrument.setAcceptDrops(True)
        self.StE_Part_Harmony_Instrument.setStyleSheet("padding: 1px;\n"
"border: 1px solid;\n"
"border-color: #1e1e1e;\n"
"background-color: #242424;")
        self.StE_Part_Harmony_Instrument.setText("")
        self.StE_Part_Harmony_Instrument.setObjectName("StE_Part_Harmony_Instrument")
        self.StE_Parts_List.addWidget(self.StE_Part_Harmony_Instrument, 1, 1, 1, 1)
        self.StE_Part_Chords_Label = QtWidgets.QLabel(self.StE_Parts)
        self.StE_Part_Chords_Label.setObjectName("StE_Part_Chords_Label")
        self.StE_Parts_List.addWidget(self.StE_Part_Chords_Label, 2, 0, 1, 1)
        self.StE_Part_Percussion2_Label = QtWidgets.QLabel(self.StE_Parts)
        self.StE_Part_Percussion2_Label.setObjectName("StE_Part_Percussion2_Label")
        self.StE_Parts_List.addWidget(self.StE_Part_Percussion2_Label, 5, 0, 1, 1)
        self.StE_Part_Percussion2_Instrument = QtWidgets.QLabel(self.StE_Parts)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.StE_Part_Percussion2_Instrument.setFont(font)
        self.StE_Part_Percussion2_Instrument.setAcceptDrops(True)
        self.StE_Part_Percussion2_Instrument.setStyleSheet("padding: 1px;\n"
"border: 1px solid;\n"
"border-color: #1e1e1e;\n"
"background-color: #242424;")
        self.StE_Part_Percussion2_Instrument.setText("")
        self.StE_Part_Percussion2_Instrument.setObjectName("StE_Part_Percussion2_Instrument")
        self.StE_Parts_List.addWidget(self.StE_Part_Percussion2_Instrument, 5, 1, 1, 1)
        self.StE_Part_Melody_Instrument = QtWidgets.QLabel(self.StE_Parts)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StE_Part_Melody_Instrument.sizePolicy().hasHeightForWidth())
        self.StE_Part_Melody_Instrument.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.StE_Part_Melody_Instrument.setFont(font)
        self.StE_Part_Melody_Instrument.setAcceptDrops(True)
        self.StE_Part_Melody_Instrument.setStyleSheet("padding: 1px;\n"
"border: 1px solid;\n"
"border-color: #1e1e1e;\n"
"background-color: #242424;")
        self.StE_Part_Melody_Instrument.setText("")
        self.StE_Part_Melody_Instrument.setObjectName("StE_Part_Melody_Instrument")
        self.StE_Parts_List.addWidget(self.StE_Part_Melody_Instrument, 0, 1, 1, 1)
        self.StE_Part_Melody_Label = QtWidgets.QLabel(self.StE_Parts)
        self.StE_Part_Melody_Label.setObjectName("StE_Part_Melody_Label")
        self.StE_Parts_List.addWidget(self.StE_Part_Melody_Label, 0, 0, 1, 1)
        self.verticalLayout_7.addLayout(self.StE_Parts_List)
        self.StE_ResetStyle = QtWidgets.QPushButton(self.StE_Parts)
        self.StE_ResetStyle.setObjectName("StE_ResetStyle")
        self.verticalLayout_7.addWidget(self.StE_ResetStyle)
        self.StE_PartsAndFile.addWidget(self.StE_Parts)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.StE_PartsAndFile.addItem(spacerItem5)
        self.StE_Patch = QtWidgets.QPushButton(self.StyleEditor)
        self.StE_Patch.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(20)
        self.StE_Patch.setFont(font)
        self.StE_Patch.setObjectName("StE_Patch")
        self.StE_PartsAndFile.addWidget(self.StE_Patch)
        self.StE_MainLayout.addLayout(self.StE_PartsAndFile)
        self.StE_Instruments = QtWidgets.QGroupBox(self.StyleEditor)
        self.StE_Instruments.setMaximumSize(QtCore.QSize(300, 16777215))
        self.StE_Instruments.setObjectName("StE_Instruments")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.StE_Instruments)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.StE_InstrumentList = QtWidgets.QListWidget(self.StE_Instruments)
        self.StE_InstrumentList.setObjectName("StE_InstrumentList")
        self.verticalLayout_32.addWidget(self.StE_InstrumentList)
        self.StE_PartSelector_Layout = QtWidgets.QHBoxLayout()
        self.StE_PartSelector_Layout.setObjectName("StE_PartSelector_Layout")
        self.StE_PartSelector_Label = QtWidgets.QLabel(self.StE_Instruments)
        self.StE_PartSelector_Label.setObjectName("StE_PartSelector_Label")
        self.StE_PartSelector_Layout.addWidget(self.StE_PartSelector_Label)
        self.StE_PartSelector = QtWidgets.QComboBox(self.StE_Instruments)
        self.StE_PartSelector.setObjectName("StE_PartSelector")
        self.StE_PartSelector.addItem("")
        self.StE_PartSelector.addItem("")
        self.StE_PartSelector.addItem("")
        self.StE_PartSelector.addItem("")
        self.StE_PartSelector.addItem("")
        self.StE_PartSelector.addItem("")
        self.StE_PartSelector_Layout.addWidget(self.StE_PartSelector)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.StE_PartSelector_Layout.addItem(spacerItem6)
        self.verticalLayout_32.addLayout(self.StE_PartSelector_Layout)
        self.StE_MainLayout.addWidget(self.StE_Instruments)
        self.StE_Styles = QtWidgets.QGroupBox(self.StyleEditor)
        self.StE_Styles.setMaximumSize(QtCore.QSize(300, 16777215))
        self.StE_Styles.setObjectName("StE_Styles")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.StE_Styles)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.StE_StyleList = QtWidgets.QListWidget(self.StE_Styles)
        self.StE_StyleList.setObjectName("StE_StyleList")
        self.verticalLayout_13.addWidget(self.StE_StyleList)
        self.StE_ChangeStyleName_Layout = QtWidgets.QHBoxLayout()
        self.StE_ChangeStyleName_Layout.setObjectName("StE_ChangeStyleName_Layout")
        self.StE_ChangeStyleName_Label = QtWidgets.QLabel(self.StE_Styles)
        self.StE_ChangeStyleName_Label.setObjectName("StE_ChangeStyleName_Label")
        self.StE_ChangeStyleName_Layout.addWidget(self.StE_ChangeStyleName_Label)
        self.StE_ChangeStyleName = QtWidgets.QLineEdit(self.StE_Styles)
        self.StE_ChangeStyleName.setMaximumSize(QtCore.QSize(16777215, 20))
        self.StE_ChangeStyleName.setText("")
        self.StE_ChangeStyleName.setObjectName("StE_ChangeStyleName")
        self.StE_ChangeStyleName_Layout.addWidget(self.StE_ChangeStyleName)
        self.verticalLayout_13.addLayout(self.StE_ChangeStyleName_Layout)
        self.StE_MainLayout.addWidget(self.StE_Styles)
        self.verticalLayout_10.addLayout(self.StE_MainLayout)
        self.MainWidget.addWidget(self.StyleEditor)
        self.TextEditor = QtWidgets.QWidget()
        self.TextEditor.setObjectName("TextEditor")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.TextEditor)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.TE_Title = QtWidgets.QHBoxLayout()
        self.TE_Title.setObjectName("TE_Title")
        self.TE_Title_Label = QtWidgets.QLabel(self.TextEditor)
        self.TE_Title_Label.setMaximumSize(QtCore.QSize(16777215, 44))
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(26)
        self.TE_Title_Label.setFont(font)
        self.TE_Title_Label.setObjectName("TE_Title_Label")
        self.TE_Title.addWidget(self.TE_Title_Label)
        self.TE_Back_Button = QtWidgets.QPushButton(self.TextEditor)
        self.TE_Back_Button.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TE_Back_Button.setFont(font)
        self.TE_Back_Button.setObjectName("TE_Back_Button")
        self.TE_Title.addWidget(self.TE_Back_Button)
        self.verticalLayout_12.addLayout(self.TE_Title)
        self.TE_Text = QtWidgets.QPlainTextEdit(self.TextEditor)
        self.TE_Text.setObjectName("TE_Text")
        self.verticalLayout_12.addWidget(self.TE_Text)
        self.TE_Buttons = QtWidgets.QHBoxLayout()
        self.TE_Buttons.setObjectName("TE_Buttons")
        self.TE_OpenExternal = QtWidgets.QPushButton(self.TextEditor)
        self.TE_OpenExternal.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(20)
        self.TE_OpenExternal.setFont(font)
        self.TE_OpenExternal.setObjectName("TE_OpenExternal")
        self.TE_Buttons.addWidget(self.TE_OpenExternal)
        self.TE_Patch = QtWidgets.QPushButton(self.TextEditor)
        self.TE_Patch.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(20)
        self.TE_Patch.setFont(font)
        self.TE_Patch.setObjectName("TE_Patch")
        self.TE_Buttons.addWidget(self.TE_Patch)
        self.verticalLayout_12.addLayout(self.TE_Buttons)
        self.MainWidget.addWidget(self.TextEditor)
        self.DefaultStyleEditor = QtWidgets.QWidget()
        self.DefaultStyleEditor.setObjectName("DefaultStyleEditor")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.DefaultStyleEditor)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.DS_Title = QtWidgets.QHBoxLayout()
        self.DS_Title.setObjectName("DS_Title")
        self.DS_Title_Label = QtWidgets.QLabel(self.DefaultStyleEditor)
        self.DS_Title_Label.setMaximumSize(QtCore.QSize(16777215, 44))
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(26)
        self.DS_Title_Label.setFont(font)
        self.DS_Title_Label.setObjectName("DS_Title_Label")
        self.DS_Title.addWidget(self.DS_Title_Label)
        self.DS_Back_Button = QtWidgets.QPushButton(self.DefaultStyleEditor)
        self.DS_Back_Button.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.DS_Back_Button.setFont(font)
        self.DS_Back_Button.setObjectName("DS_Back_Button")
        self.DS_Title.addWidget(self.DS_Back_Button)
        self.verticalLayout_14.addLayout(self.DS_Title)
        self.DS_Lists = QtWidgets.QHBoxLayout()
        self.DS_Lists.setObjectName("DS_Lists")
        self.DS_SongBox = QtWidgets.QGroupBox(self.DefaultStyleEditor)
        self.DS_SongBox.setObjectName("DS_SongBox")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.DS_SongBox)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.DS_Songs = QtWidgets.QListWidget(self.DS_SongBox)
        self.DS_Songs.setObjectName("DS_Songs")
        self.verticalLayout_15.addWidget(self.DS_Songs)
        self.DS_Lists.addWidget(self.DS_SongBox)
        self.DS_StyleBox = QtWidgets.QGroupBox(self.DefaultStyleEditor)
        self.DS_StyleBox.setObjectName("DS_StyleBox")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.DS_StyleBox)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.DS_Styles = QtWidgets.QListWidget(self.DS_StyleBox)
        self.DS_Styles.setObjectName("DS_Styles")
        self.verticalLayout_16.addWidget(self.DS_Styles)
        self.DS_Reset = QtWidgets.QPushButton(self.DS_StyleBox)
        self.DS_Reset.setObjectName("DS_Reset")
        self.verticalLayout_16.addWidget(self.DS_Reset)
        self.DS_Lists.addWidget(self.DS_StyleBox)
        self.verticalLayout_14.addLayout(self.DS_Lists)
        self.DS_Patch = QtWidgets.QPushButton(self.DefaultStyleEditor)
        self.DS_Patch.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(20)
        self.DS_Patch.setFont(font)
        self.DS_Patch.setObjectName("DS_Patch")
        self.verticalLayout_14.addWidget(self.DS_Patch)
        self.MainWidget.addWidget(self.DefaultStyleEditor)
        self.RemoveSong = QtWidgets.QWidget()
        self.RemoveSong.setObjectName("RemoveSong")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.RemoveSong)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.RS_Title = QtWidgets.QHBoxLayout()
        self.RS_Title.setObjectName("RS_Title")
        self.RS_Title_Label = QtWidgets.QLabel(self.RemoveSong)
        self.RS_Title_Label.setMaximumSize(QtCore.QSize(16777215, 44))
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(26)
        self.RS_Title_Label.setFont(font)
        self.RS_Title_Label.setObjectName("RS_Title_Label")
        self.RS_Title.addWidget(self.RS_Title_Label)
        self.RS_Back_Button = QtWidgets.QPushButton(self.RemoveSong)
        self.RS_Back_Button.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RS_Back_Button.setFont(font)
        self.RS_Back_Button.setObjectName("RS_Back_Button")
        self.RS_Title.addWidget(self.RS_Back_Button)
        self.verticalLayout_20.addLayout(self.RS_Title)
        self.RS_SongBox = QtWidgets.QGroupBox(self.RemoveSong)
        self.RS_SongBox.setObjectName("RS_SongBox")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.RS_SongBox)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.RS_Songs = QtWidgets.QListWidget(self.RS_SongBox)
        self.RS_Songs.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.RS_Songs.setMovement(QtWidgets.QListView.Static)
        self.RS_Songs.setObjectName("RS_Songs")
        self.verticalLayout_19.addWidget(self.RS_Songs)
        self.verticalLayout_20.addWidget(self.RS_SongBox)
        self.RS_Buttons = QtWidgets.QHBoxLayout()
        self.RS_Buttons.setObjectName("RS_Buttons")
        self.RS_RemoveCustomSongs = QtWidgets.QPushButton(self.RemoveSong)
        self.RS_RemoveCustomSongs.setObjectName("RS_RemoveCustomSongs")
        self.RS_Buttons.addWidget(self.RS_RemoveCustomSongs)
        self.RS_Deselect_Button = QtWidgets.QPushButton(self.RemoveSong)
        self.RS_Deselect_Button.setObjectName("RS_Deselect_Button")
        self.RS_Buttons.addWidget(self.RS_Deselect_Button)
        self.verticalLayout_20.addLayout(self.RS_Buttons)
        self.RS_Patch = QtWidgets.QPushButton(self.RemoveSong)
        self.RS_Patch.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(20)
        self.RS_Patch.setFont(font)
        self.RS_Patch.setObjectName("RS_Patch")
        self.verticalLayout_20.addWidget(self.RS_Patch)
        self.MainWidget.addWidget(self.RemoveSong)
        self.SoundEditor = QtWidgets.QWidget()
        self.SoundEditor.setObjectName("SoundEditor")
        self.verticalLayout_44 = QtWidgets.QVBoxLayout(self.SoundEditor)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.SOE_Title = QtWidgets.QHBoxLayout()
        self.SOE_Title.setObjectName("SOE_Title")
        self.SOE_Title_Label = QtWidgets.QLabel(self.SoundEditor)
        self.SOE_Title_Label.setMaximumSize(QtCore.QSize(16777215, 44))
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(26)
        self.SOE_Title_Label.setFont(font)
        self.SOE_Title_Label.setObjectName("SOE_Title_Label")
        self.SOE_Title.addWidget(self.SOE_Title_Label)
        self.SOE_Back_Button = QtWidgets.QPushButton(self.SoundEditor)
        self.SOE_Back_Button.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SOE_Back_Button.setFont(font)
        self.SOE_Back_Button.setObjectName("SOE_Back_Button")
        self.SOE_Title.addWidget(self.SOE_Back_Button)
        self.verticalLayout_44.addLayout(self.SOE_Title)
        self.SOE_Lists = QtWidgets.QHBoxLayout()
        self.SOE_Lists.setObjectName("SOE_Lists")
        self.SOE_SoundBox = QtWidgets.QGroupBox(self.SoundEditor)
        self.SOE_SoundBox.setObjectName("SOE_SoundBox")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.SOE_SoundBox)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.SOE_Sounds = QtWidgets.QListWidget(self.SOE_SoundBox)
        self.SOE_Sounds.setObjectName("SOE_Sounds")
        self.verticalLayout_42.addWidget(self.SOE_Sounds)
        self.SOE_Lists.addWidget(self.SOE_SoundBox)
        self.SOE_RightLayout = QtWidgets.QVBoxLayout()
        self.SOE_RightLayout.setObjectName("SOE_RightLayout")
        self.SOE_File = QtWidgets.QGroupBox(self.SoundEditor)
        self.SOE_File.setObjectName("SOE_File")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.SOE_File)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SOE_File_Label = QtWidgets.QLabel(self.SOE_File)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SOE_File_Label.sizePolicy().hasHeightForWidth())
        self.SOE_File_Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SOE_File_Label.setFont(font)
        self.SOE_File_Label.setAcceptDrops(True)
        self.SOE_File_Label.setStyleSheet("QLabel\n"
"{\n"
"padding: 1px;\n"
"border: 1px solid;\n"
"border-color: #1e1e1e;\n"
"background-color: #242424;\n"
"padding-top: 6px;\n"
"padding-bottom: 6px;\n"
"}")
        self.SOE_File_Label.setObjectName("SOE_File_Label")
        self.horizontalLayout.addWidget(self.SOE_File_Label)
        self.SOE_File_Browse = QtWidgets.QPushButton(self.SOE_File)
        self.SOE_File_Browse.setMinimumSize(QtCore.QSize(100, 0))
        self.SOE_File_Browse.setObjectName("SOE_File_Browse")
        self.horizontalLayout.addWidget(self.SOE_File_Browse)
        self.SOE_RightLayout.addWidget(self.SOE_File)
        self.SOE_SoundTypeBox = QtWidgets.QGroupBox(self.SoundEditor)
        self.SOE_SoundTypeBox.setObjectName("SOE_SoundTypeBox")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout(self.SOE_SoundTypeBox)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.SOE_SoundType = QtWidgets.QListWidget(self.SOE_SoundTypeBox)
        self.SOE_SoundType.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.SOE_SoundType.setMovement(QtWidgets.QListView.Static)
        self.SOE_SoundType.setObjectName("SOE_SoundType")
        self.verticalLayout_43.addWidget(self.SOE_SoundType)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SOE_SelectAll = QtWidgets.QPushButton(self.SOE_SoundTypeBox)
        self.SOE_SelectAll.setObjectName("SOE_SelectAll")
        self.horizontalLayout_2.addWidget(self.SOE_SelectAll)
        self.SOE_PlayAudio = QtWidgets.QPushButton(self.SOE_SoundTypeBox)
        self.SOE_PlayAudio.setObjectName("SOE_PlayAudio")
        self.horizontalLayout_2.addWidget(self.SOE_PlayAudio)
        self.verticalLayout_43.addLayout(self.horizontalLayout_2)
        self.SOE_RightLayout.addWidget(self.SOE_SoundTypeBox)
        self.SOE_Lists.addLayout(self.SOE_RightLayout)
        self.verticalLayout_44.addLayout(self.SOE_Lists)
        self.SOE_Patch = QtWidgets.QPushButton(self.SoundEditor)
        self.SOE_Patch.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(20)
        self.SOE_Patch.setFont(font)
        self.SOE_Patch.setObjectName("SOE_Patch")
        self.verticalLayout_44.addWidget(self.SOE_Patch)
        self.MainWidget.addWidget(self.SoundEditor)
        self.verticalLayout_17.addWidget(self.MainWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.MB_Options = QtWidgets.QMenu(self.menubar)
        self.MB_Options.setObjectName("MB_Options")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.MB_LoadFile = QtWidgets.QAction(MainWindow)
        self.MB_LoadFile.setObjectName("MB_LoadFile")
        self.MB_LoadFolder = QtWidgets.QAction(MainWindow)
        self.MB_LoadFolder.setObjectName("MB_LoadFolder")
        self.MB_Dolphin = QtWidgets.QAction(MainWindow)
        self.MB_Dolphin.setObjectName("MB_Dolphin")
        self.MB_DolphinMenu = QtWidgets.QAction(MainWindow)
        self.MB_DolphinMenu.setObjectName("MB_DolphinMenu")
        self.MB_Updates = QtWidgets.QAction(MainWindow)
        self.MB_Updates.setObjectName("MB_Updates")
        self.MB_Settings = QtWidgets.QAction(MainWindow)
        self.MB_Settings.setObjectName("MB_Settings")
        self.MB_DownloadSongs = QtWidgets.QAction(MainWindow)
        self.MB_DownloadSongs.setObjectName("MB_DownloadSongs")
        self.MB_Help = QtWidgets.QAction(MainWindow)
        self.MB_Help.setObjectName("MB_Help")
        self.MB_SaveFolder = QtWidgets.QAction(MainWindow)
        self.MB_SaveFolder.setObjectName("MB_SaveFolder")
        self.MB_SaveFile = QtWidgets.QAction(MainWindow)
        self.MB_SaveFile.setObjectName("MB_SaveFile")
        self.MB_Documentation = QtWidgets.QAction(MainWindow)
        self.MB_Documentation.setObjectName("MB_Documentation")
        self.MB_About = QtWidgets.QAction(MainWindow)
        self.MB_About.setObjectName("MB_About")
        self.MB_Donate = QtWidgets.QAction(MainWindow)
        self.MB_Donate.setObjectName("MB_Donate")
        self.menuFile.addAction(self.MB_LoadFile)
        self.menuFile.addAction(self.MB_LoadFolder)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.MB_Dolphin)
        self.menuFile.addAction(self.MB_DolphinMenu)
        self.menuFile.addSeparator()
        self.MB_Options.addAction(self.MB_Settings)
        self.MB_Options.addSeparator()
        self.MB_Options.addAction(self.MB_DownloadSongs)
        self.MB_Options.addAction(self.MB_SaveFile)
        self.MB_Options.addSeparator()
        self.MB_Options.addAction(self.MB_Updates)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.MB_Help)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.MB_Donate)
        self.menuHelp.addAction(self.MB_About)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.MB_Options.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.MainWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wii Music Editor Plus"))
        self.MP_Title.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/images/images/Title.png\"/></p></body></html>"))
        self.MP_LoadedFile_Label.setText(_translate("MainWindow", "Currently Loaded File:"))
        self.MP_LoadedFile_Path.setText(_translate("MainWindow", "No File Loaded"))
        self.MP_SongEditor_Button.setText(_translate("MainWindow", "Song Editor"))
        self.MP_StyleEditor_Button.setText(_translate("MainWindow", "Style Editor"))
        self.MP_Advanced.setTitle(_translate("MainWindow", "Advanced Features"))
        self.MP_EditText_Button.setText(_translate("MainWindow", "Change All Text"))
        self.MP_DefaultStyle_Button.setText(_translate("MainWindow", "Change Default Styles"))
        self.MP_ReplaceSound_Button.setText(_translate("MainWindow", "Replace Sounds"))
        self.MP_RemoveSong_Button.setText(_translate("MainWindow", "Remove Song"))
        self.MP_GeckocodeConvert_Button.setText(_translate("MainWindow", "Convert Geckocode to .gct"))
        self.MP_MainDolPatch_Button.setText(_translate("MainWindow", "Patch Main.dol with Geckocode"))
        self.MP_Riivolution_Button.setText(_translate("MainWindow", "Create Riivolution Patch"))
        self.MP_RomEditing.setTitle(_translate("MainWindow", "Rom Editing"))
        self.MP_RevertChanges_Button.setText(_translate("MainWindow", "Revert Changes"))
        self.MP_PackRom_Button.setText(_translate("MainWindow", "Pack Rom Filesystem"))
        self.MP_ImportFiles_Button.setText(_translate("MainWindow", "Import Files"))
        self.MP_ExportFiles_Button.setText(_translate("MainWindow", "Export Files"))
        self.MP_ImportChanges_Button.setText(_translate("MainWindow", "Import Changes"))
        self.SE_Title.setText(_translate("MainWindow", "Song Editor"))
        self.SE_Back_Button.setText(_translate("MainWindow", " Back"))
        self.SE_Midi.setTitle(_translate("MainWindow", "Replace Song"))
        self.SE_Midi_File_Score_Label.setText(_translate("MainWindow", "Load a Midi-Type file"))
        self.SE_Midi_File_Score_Button.setText(_translate("MainWindow", "Browse"))
        self.SE_Midi_File_Score_Title.setText(_translate("MainWindow", "SCORE:"))
        self.SE_Midi_File_Song_Label.setText(_translate("MainWindow", "Load a Midi-Type file"))
        self.SE_Midi_File_Song_Title.setText(_translate("MainWindow", "SONG:"))
        self.SE_Midi_File_Song_Button.setText(_translate("MainWindow", "Browse"))
        self.SE_Midi_File_Replace_Song.setText(_translate("MainWindow", "Replace SONG seperatly"))
        self.SE_Midi_Tempo_Label.setText(_translate("MainWindow", "Tempo:"))
        self.SE_Midi_Tempo_BPM.setText(_translate("MainWindow", "BPM"))
        self.SE_Midi_Length_Label.setText(_translate("MainWindow", "Length:"))
        self.SE_Midi_Length_Measures.setText(_translate("MainWindow", "Measures"))
        self.SE_Midi_Length_Beats.setText(_translate("MainWindow", "Beats"))
        self.SE_Midi_TimeSignature_Label.setText(_translate("MainWindow", "Time Signature:"))
        self.SE_Midi_TimeSignature_4.setText(_translate("MainWindow", "4/4"))
        self.SE_Midi_TimeSignature_3.setText(_translate("MainWindow", "3/4"))
        self.SE_ChangeSongText.setTitle(_translate("MainWindow", "Change Song Text"))
        self.SE_ChangeSongText_Name_Label.setText(_translate("MainWindow", "Name:"))
        self.SE_ChangeSongText_Genre_Label.setText(_translate("MainWindow", "Genre:"))
        self.SE_ChangeSongText_Desc_Label.setText(_translate("MainWindow", "Description:"))
        self.SE_Patch.setText(_translate("MainWindow", "Patch!"))
        self.SE_SongToChangeBox.setTitle(_translate("MainWindow", "Song to change"))
        self.SE_StyleLabel.setText(_translate("MainWindow", "Style: "))
        self.SE_OpenStyleEditor.setText(_translate("MainWindow", "Edit in Style Editor"))
        self.SE_OpenDefaultStyleEditor.setText(_translate("MainWindow", "Change Default Style"))
        self.StE_Title_Label.setText(_translate("MainWindow", "Style Editor"))
        self.StE_Back_Button.setText(_translate("MainWindow", " Back"))
        self.StE_Parts.setTitle(_translate("MainWindow", "Parts"))
        self.StE_Part_Bass_Label.setText(_translate("MainWindow", "Bass:"))
        self.StE_Part_Percussion1_Label.setText(_translate("MainWindow", "Perc 1:"))
        self.StE_Part_Harmony_Label.setText(_translate("MainWindow", "Harmony:"))
        self.StE_Part_Chords_Label.setText(_translate("MainWindow", "Chords:"))
        self.StE_Part_Percussion2_Label.setText(_translate("MainWindow", "Perc 2:"))
        self.StE_Part_Melody_Label.setText(_translate("MainWindow", "Melody:"))
        self.StE_ResetStyle.setText(_translate("MainWindow", "Reset to Default"))
        self.StE_Patch.setText(_translate("MainWindow", "Patch!"))
        self.StE_Instruments.setTitle(_translate("MainWindow", "Instruments"))
        self.StE_PartSelector_Label.setText(_translate("MainWindow", "Part to Change:"))
        self.StE_PartSelector.setItemText(0, _translate("MainWindow", "Melody"))
        self.StE_PartSelector.setItemText(1, _translate("MainWindow", "Harmony"))
        self.StE_PartSelector.setItemText(2, _translate("MainWindow", "Chords"))
        self.StE_PartSelector.setItemText(3, _translate("MainWindow", "Bass"))
        self.StE_PartSelector.setItemText(4, _translate("MainWindow", "Percussion 1"))
        self.StE_PartSelector.setItemText(5, _translate("MainWindow", "Percussion 2"))
        self.StE_Styles.setTitle(_translate("MainWindow", "Style to change"))
        self.StE_ChangeStyleName_Label.setText(_translate("MainWindow", "Style Name:"))
        self.TE_Title_Label.setText(_translate("MainWindow", "Text Editor"))
        self.TE_Back_Button.setText(_translate("MainWindow", " Back"))
        self.TE_OpenExternal.setText(_translate("MainWindow", "Open in External Editor"))
        self.TE_Patch.setText(_translate("MainWindow", "Patch!"))
        self.DS_Title_Label.setText(_translate("MainWindow", "Default Style Editor"))
        self.DS_Back_Button.setText(_translate("MainWindow", " Back"))
        self.DS_SongBox.setTitle(_translate("MainWindow", "Song List"))
        self.DS_StyleBox.setTitle(_translate("MainWindow", "Style List"))
        self.DS_Reset.setText(_translate("MainWindow", "Set to Default"))
        self.DS_Patch.setText(_translate("MainWindow", "Patch!"))
        self.RS_Title_Label.setText(_translate("MainWindow", "Remove Songs"))
        self.RS_Back_Button.setText(_translate("MainWindow", " Back"))
        self.RS_SongBox.setTitle(_translate("MainWindow", "Song List"))
        self.RS_RemoveCustomSongs.setText(_translate("MainWindow", "Remove All Non-Custom Songs"))
        self.RS_Deselect_Button.setText(_translate("MainWindow", "Deselect All"))
        self.RS_Patch.setText(_translate("MainWindow", "Purge Songs!!!"))
        self.SOE_Title_Label.setText(_translate("MainWindow", "Sound Editor"))
        self.SOE_Back_Button.setText(_translate("MainWindow", " Back"))
        self.SOE_SoundBox.setTitle(_translate("MainWindow", "Sound List"))
        self.SOE_File.setTitle(_translate("MainWindow", "File"))
        self.SOE_File_Label.setText(_translate("MainWindow", "Load a Rwav-Type file"))
        self.SOE_File_Browse.setText(_translate("MainWindow", "Browse"))
        self.SOE_SoundTypeBox.setTitle(_translate("MainWindow", "Sound Types"))
        self.SOE_SelectAll.setText(_translate("MainWindow", "Select All"))
        self.SOE_PlayAudio.setText(_translate("MainWindow", "Play Audio"))
        self.SOE_Patch.setText(_translate("MainWindow", "Patch!"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.MB_Options.setTitle(_translate("MainWindow", "Options"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.MB_LoadFile.setText(_translate("MainWindow", "Load Wii Music File"))
        self.MB_LoadFolder.setText(_translate("MainWindow", "Load Wii Music Folder"))
        self.MB_Dolphin.setText(_translate("MainWindow", "Run Dolphin"))
        self.MB_Dolphin.setShortcut(_translate("MainWindow", "F5"))
        self.MB_DolphinMenu.setText(_translate("MainWindow", "Run Dolphin (Menu)"))
        self.MB_DolphinMenu.setToolTip(_translate("MainWindow", "Run Dolphin (Menu)"))
        self.MB_DolphinMenu.setShortcut(_translate("MainWindow", "F6"))
        self.MB_Updates.setText(_translate("MainWindow", "Check for Updates"))
        self.MB_Settings.setText(_translate("MainWindow", "Settings"))
        self.MB_DownloadSongs.setText(_translate("MainWindow", "Download Pre-made Songs"))
        self.MB_Help.setText(_translate("MainWindow", "Open Wiki"))
        self.MB_SaveFolder.setText(_translate("MainWindow", "Open Save Folder"))
        self.MB_SaveFile.setText(_translate("MainWindow", "Add 100% Save File to Dolphin"))
        self.MB_Documentation.setText(_translate("MainWindow", "Game Documentation"))
        self.MB_About.setText(_translate("MainWindow", "About"))
        self.MB_Donate.setText(_translate("MainWindow", "Donate"))
import resources_rc
