# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WiiMusicPlus.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(698, 547)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 16, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 21, 21))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 16, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 16, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 21, 21))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 16, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 16, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 21, 21))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 32, 32))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setStyleSheet("QToolTip\n"
"{\n"
"     border: 1px solid black;\n"
"     background-color: #ffa02f;\n"
"     padding: 1px;\n"
"     border-radius: 3px;\n"
"     opacity: 100;\n"
"}\n"
"\n"
"QWidget\n"
"{\n"
"    color: white;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QWidget:item:hover\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #ca0619);\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:item:selected\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QMenuBar\n"
"{\n"
"    background: #242424;\n"
"}\n"
"\n"
"QMenuBar::item\n"
"{\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected\n"
"{\n"
"    background: transparent;\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"QMenuBar::item:pressed\n"
"{\n"
"    background: #444;\n"
"    border: 1px solid #000;\n"
"    background-color: QLinearGradient(\n"
"        x1:0, y1:0,\n"
"        x2:0, y2:1,\n"
"        stop:1 #212121,\n"
"        stop:0.4 #343434/*,\n"
"        stop:0.2 #343434,\n"
"        stop:0.1 #ffaa00*/\n"
"    );\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"}\n"
"\n"
"QMenu\n"
"{\n"
"    border: 1px solid #000;\n"
"}\n"
"\n"
"QMenu::item\n"
"{\n"
"    padding: 2px 20px 2px 20px;\n"
"}\n"
"\n"
"QMenu::item:selected\n"
"{\n"
"    color: #000000;\n"
"}\n"
"\n"
"QWidget:disabled\n"
"{\n"
"    color: #404040;\n"
"    background-color: #323232;\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #4d4d4d, stop: 0 #646464, stop: 1 #5d5d5d);\n"
"    padding: 1px;\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    color: white;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-width: 1px;\n"
"    border-color: #1e1e1e;\n"
"    border-style: solid;\n"
"    border-radius: 6;\n"
"    padding: 3px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"}\n"
"\n"
"QComboBox\n"
"{\n"
"    selection-background-color: #ffaa00;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #565656, stop: 0.1 #525252, stop: 0.5 #4e4e4e, stop: 0.9 #4a4a4a, stop: 1 #464646);\n"
"    border-style: solid;\n"
"    border: 1px solid #1e1e1e;\n"
"    border-radius: 5;\n"
"}\n"
"\n"
"QComboBox:hover,QPushButton:hover\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #2d2d2d, stop: 0.1 #2b2b2b, stop: 0.5 #292929, stop: 0.9 #282828, stop: 1 #252525);\n"
"    selection-background-color: #ffaa00;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    border: 2px solid darkgray;\n"
"    selection-background-color: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"     subcontrol-origin: padding;\n"
"     subcontrol-position: top right;\n"
"     width: 15px;\n"
"\n"
"     border-left-width: 0px;\n"
"     border-left-color: darkgray;\n"
"     border-left-style: solid; /* just a single line */\n"
"     border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"     border-bottom-right-radius: 3px;\n"
" }\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"     image: url(:/down_arrow.png);\n"
"}\n"
"\n"
"QGroupBox:focus\n"
"{\n"
"border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QTextEdit:focus\n"
"{\n"
"    border: 2px solid QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"     border: 1px solid #222222;\n"
"     background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"     height: 7px;\n"
"     margin: 0px 16px 0 16px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"      subcontrol-position: right;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      width: 14px;\n"
"     subcontrol-position: left;\n"
"     subcontrol-origin: margin;\n"
"}\n"
"\n"
"QAbstractItemView\n"
"{\n"
"    background-color: #121212;\n"
"}\n"
"\n"
"QScrollBar::right-arrow:horizontal, QScrollBar::left-arrow:horizontal\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 1, y2: 0, stop: 0.0 #121212, stop: 0.2 #282828, stop: 1 #484848);\n"
"      width: 7px;\n"
"      margin: 16px 0 16px 0;\n"
"      border: 1px solid #222222;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical\n"
"{\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 0.5 #d7801a, stop: 1 #ffa02f);\n"
"      min-height: 20px;\n"
"      border-radius: 2px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #ffa02f, stop: 1 #d7801a);\n"
"      height: 14px;\n"
"      subcontrol-position: bottom;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"      border: 1px solid #1b1b19;\n"
"      border-radius: 2px;\n"
"      background: QLinearGradient( x1: 0, y1: 0, x2: 0, y2: 1, stop: 0 #d7801a, stop: 1 #ffa02f);\n"
"      height: 14px;\n"
"      subcontrol-position: top;\n"
"      subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"{\n"
"      border: 1px solid black;\n"
"      width: 1px;\n"
"      height: 1px;\n"
"      background: white;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"      background: none;\n"
"}\n"
"\n"
"QTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"    padding-left: 1px;\n"
"}\n"
"\n"
"QPlainTextEdit\n"
"{\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QHeaderView::section\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #616161, stop: 0.5 #505050, stop: 0.6 #434343, stop:1 #656565);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"}\n"
"\n"
"QCheckBox:disabled\n"
"{\n"
"color: #414141;\n"
"}\n"
"\n"
"QDockWidget::title\n"
"{\n"
"    text-align: center;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button, QDockWidget::float-button\n"
"{\n"
"    text-align: center;\n"
"    spacing: 1px; /* spacing between items in the tool bar */\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #323232, stop: 0.5 #242424, stop:1 #323232);\n"
"}\n"
"\n"
"QDockWidget::close-button:hover, QDockWidget::float-button:hover\n"
"{\n"
"    background: #242424;\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed, QDockWidget::float-button:pressed\n"
"{\n"
"    padding: 1px -1px -1px 1px;\n"
"}\n"
"\n"
"QMainWindow::separator\n"
"{\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #4c4c4c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QMainWindow::separator:hover\n"
"{\n"
"\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #d7801a, stop:0.5 #b56c17 stop:1 #ffa02f);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    border: 1px solid #6c6c6c;\n"
"    spacing: 3px; /* spacing between items in the tool bar */\n"
"}\n"
"\n"
"QToolBar::handle\n"
"{\n"
"     spacing: 3px; /* spacing between items in the tool bar */\n"
"     background: url(:/images/handle.png);\n"
"}\n"
"\n"
"QMenu::separator\n"
"{\n"
"    height: 2px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:0 #161616, stop: 0.5 #151515, stop: 0.6 #212121, stop:1 #343434);\n"
"    color: white;\n"
"    padding-left: 4px;\n"
"    margin-left: 10px;\n"
"    margin-right: 5px;\n"
"}\n"
"\n"
"QProgressBar\n"
"{\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: #d7801a;\n"
"    width: 2.15px;\n"
"    margin: 0.5px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    color: #b1b1b1;\n"
"    border: 1px solid #444;\n"
"    border-bottom-style: none;\n"
"    background-color: #323232;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    padding-top: 3px;\n"
"    padding-bottom: 2px;\n"
"    margin-right: -1px;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid #444;\n"
"    top: 1px;\n"
"}\n"
"\n"
"QTabBar::tab:last\n"
"{\n"
"    margin-right: 0; /* the last selected tab has nothing to overlap with on the right */\n"
"    border-top-right-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:first:!selected\n"
"{\n"
" margin-left: 0px; /* the last selected tab has nothing to overlap with on the right */\n"
"\n"
"\n"
"    border-top-left-radius: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected\n"
"{\n"
"    color: #b1b1b1;\n"
"    border-bottom-style: solid;\n"
"    margin-top: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:.4 #343434);\n"
"}\n"
"\n"
"QTabBar::tab:selected\n"
"{\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    margin-bottom: 0px;\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover\n"
"{\n"
"    /*border-top: 2px solid #ffaa00;\n"
"    padding-bottom: 3px;*/\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    background-color: QLinearGradient(x1:0, y1:0, x2:0, y2:1, stop:1 #212121, stop:0.4 #343434, stop:0.2 #343434, stop:0.1 #ffaa00);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked, QRadioButton::indicator:unchecked{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked\n"
"{\n"
"    background-color: qradialgradient(\n"
"        cx: 0.5, cy: 0.5,\n"
"        fx: 0.5, fy: 0.5,\n"
"        radius: 1.0,\n"
"        stop: 0.25 #ffaa00,\n"
"        stop: 0.3 #323232\n"
"    );\n"
"}\n"
"\n"
"QCheckBox::indicator{\n"
"    color: #b1b1b1;\n"
"    background-color: #323232;\n"
"    border: 1px solid #b1b1b1;\n"
"    width: 9px;\n"
"    height: 9px;\n"
"}\n"
"\n"
"QRadioButton::indicator\n"
"{\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:hover, QCheckBox::indicator:hover\n"
"{\n"
"    border: 1px solid #ffaa00;\n"
"}\n"
"\n"
"QRadioButton:disabled\n"
"{\n"
"    background-color: #404040;\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image:url(:/images/checkbox.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled, QRadioButton::indicator:disabled\n"
"{\n"
"    border: 1px solid #444;\n"
"}\n"
"\n"
"QWidget[error=\"true\"]\n"
"{\n"
"    border: 1px solid red;\n"
"}\n"
"\n"
"QWidget[error=\"true\"]\n"
"{\n"
"    border: 1px solid red;\n"
"}")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 16, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 21, 21))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 16, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 16, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 21, 21))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 16, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 48, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(16, 16, 16))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 21, 21))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(32, 32, 32))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(64, 64, 64))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.centralwidget.setPalette(palette)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MainWidget = QtWidgets.QStackedWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Continuum Bold")
        font.setPointSize(72)
        self.MainWidget.setFont(font)
        self.MainWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.MainWidget.setObjectName("MainWidget")
        self.MainPage = QtWidgets.QWidget()
        self.MainPage.setObjectName("MainPage")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.MainPage)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.MP_Title = QtWidgets.QLabel(self.MainPage)
        self.MP_Title.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(26)
        self.MP_Title.setFont(font)
        self.MP_Title.setScaledContents(False)
        self.MP_Title.setObjectName("MP_Title")
        self.verticalLayout_9.addWidget(self.MP_Title)
        self.MP_vLine = QtWidgets.QFrame(self.MainPage)
        self.MP_vLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.MP_vLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.MP_vLine.setObjectName("MP_vLine")
        self.verticalLayout_9.addWidget(self.MP_vLine)
        self.MP_LoadedFile_Label = QtWidgets.QLabel(self.MainPage)
        self.MP_LoadedFile_Label.setObjectName("MP_LoadedFile_Label")
        self.verticalLayout_9.addWidget(self.MP_LoadedFile_Label)
        self.MP_LoadedFile_Path = QtWidgets.QLabel(self.MainPage)
        self.MP_LoadedFile_Path.setMinimumSize(QtCore.QSize(0, 26))
        self.MP_LoadedFile_Path.setMaximumSize(QtCore.QSize(16777215, 26))
        self.MP_LoadedFile_Path.setStyleSheet("QLabel\n"
"{\n"
"padding: 1px;\n"
"border: 1px solid;\n"
"border-color: #1e1e1e;\n"
"background-color: #242424;\n"
"}\n"
"\n"
"QLabel[error=\"true\"]\n"
"{\n"
"padding: 1px;\n"
"border: 1px solid;\n"
"border-color: red;\n"
"background-color: #242424;\n"
"}")
        self.MP_LoadedFile_Path.setObjectName("MP_LoadedFile_Path")
        self.verticalLayout_9.addWidget(self.MP_LoadedFile_Path)
        self.MP_HLayout1 = QtWidgets.QHBoxLayout()
        self.MP_HLayout1.setObjectName("MP_HLayout1")
        self.MP_SongEditor_Button = QtWidgets.QPushButton(self.MainPage)
        self.MP_SongEditor_Button.setMinimumSize(QtCore.QSize(0, 48))
        font = QtGui.QFont()
        font.setFamily("Continuum Bold")
        font.setPointSize(26)
        self.MP_SongEditor_Button.setFont(font)
        self.MP_SongEditor_Button.setObjectName("MP_SongEditor_Button")
        self.MP_HLayout1.addWidget(self.MP_SongEditor_Button)
        self.MP_StyleEditor_Button = QtWidgets.QPushButton(self.MainPage)
        self.MP_StyleEditor_Button.setMinimumSize(QtCore.QSize(0, 48))
        font = QtGui.QFont()
        font.setFamily("Continuum Bold")
        font.setPointSize(26)
        self.MP_StyleEditor_Button.setFont(font)
        self.MP_StyleEditor_Button.setObjectName("MP_StyleEditor_Button")
        self.MP_HLayout1.addWidget(self.MP_StyleEditor_Button)
        self.verticalLayout_9.addLayout(self.MP_HLayout1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.MainWidget.addWidget(self.MainPage)
        self.SongEditor = QtWidgets.QWidget()
        self.SongEditor.setObjectName("SongEditor")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.SongEditor)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Title = QtWidgets.QHBoxLayout()
        self.Title.setObjectName("Title")
        self.SE_Title = QtWidgets.QLabel(self.SongEditor)
        self.SE_Title.setMaximumSize(QtCore.QSize(16777215, 44))
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(26)
        self.SE_Title.setFont(font)
        self.SE_Title.setObjectName("SE_Title")
        self.Title.addWidget(self.SE_Title)
        self.SE_Back_Button = QtWidgets.QPushButton(self.SongEditor)
        self.SE_Back_Button.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SE_Back_Button.setFont(font)
        self.SE_Back_Button.setObjectName("SE_Back_Button")
        self.Title.addWidget(self.SE_Back_Button)
        self.verticalLayout_2.addLayout(self.Title)
        self.SE_MainLayout = QtWidgets.QHBoxLayout()
        self.SE_MainLayout.setObjectName("SE_MainLayout")
        self.SE_MidiAndText = QtWidgets.QVBoxLayout()
        self.SE_MidiAndText.setObjectName("SE_MidiAndText")
        self.SE_Midi = QtWidgets.QGroupBox(self.SongEditor)
        self.SE_Midi.setEnabled(True)
        self.SE_Midi.setMaximumSize(QtCore.QSize(16777215, 162))
        self.SE_Midi.setFocusPolicy(QtCore.Qt.NoFocus)
        self.SE_Midi.setCheckable(True)
        self.SE_Midi.setObjectName("SE_Midi")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.SE_Midi)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.SE_Midi_File_Label = QtWidgets.QLabel(self.SE_Midi)
        self.SE_Midi_File_Label.setMinimumSize(QtCore.QSize(0, 26))
        self.SE_Midi_File_Label.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.SE_Midi_File_Label.setFont(font)
        self.SE_Midi_File_Label.setAcceptDrops(True)
        self.SE_Midi_File_Label.setStyleSheet("QLabel\n"
"{\n"
"padding: 1px;\n"
"border: 1px solid;\n"
"border-color: #1e1e1e;\n"
"background-color: #242424;\n"
"}\n"
"\n"
"QLabel[error=\"true\"]\n"
"{\n"
"padding: 1px;\n"
"border: 1px solid;\n"
"border-color: red;\n"
"background-color: #242424;\n"
"}")
        self.SE_Midi_File_Label.setObjectName("SE_Midi_File_Label")
        self.verticalLayout_4.addWidget(self.SE_Midi_File_Label)
        self.SE_Midi_File_Button = QtWidgets.QPushButton(self.SE_Midi)
        font = QtGui.QFont()
        self.SE_Midi_File_Button.setFont(font)
        self.SE_Midi_File_Button.setObjectName("SE_Midi_File_Button")
        self.verticalLayout_4.addWidget(self.SE_Midi_File_Button)
        self.SE_Midi_hLine = QtWidgets.QFrame(self.SE_Midi)
        self.SE_Midi_hLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.SE_Midi_hLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.SE_Midi_hLine.setObjectName("SE_Midi_hLine")
        self.verticalLayout_4.addWidget(self.SE_Midi_hLine)
        self.SE_Midi_Info = QtWidgets.QHBoxLayout()
        self.SE_Midi_Info.setObjectName("SE_Midi_Info")
        self.SE_Midi_Tempo = QtWidgets.QFrame(self.SE_Midi)
        self.SE_Midi_Tempo.setMaximumSize(QtCore.QSize(129, 16777215))
        self.SE_Midi_Tempo.setObjectName("SE_Midi_Tempo")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.SE_Midi_Tempo)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SE_Midi_Tempo_Label = QtWidgets.QLabel(self.SE_Midi_Tempo)
        self.SE_Midi_Tempo_Label.setObjectName("SE_Midi_Tempo_Label")
        self.verticalLayout.addWidget(self.SE_Midi_Tempo_Label)
        self.SE_Midi_Tempo_Layout = QtWidgets.QHBoxLayout()
        self.SE_Midi_Tempo_Layout.setObjectName("SE_Midi_Tempo_Layout")
        self.SE_Midi_Tempo_Input = QtWidgets.QLineEdit(self.SE_Midi_Tempo)
        self.SE_Midi_Tempo_Input.setObjectName("SE_Midi_Tempo_Input")
        self.SE_Midi_Tempo_Layout.addWidget(self.SE_Midi_Tempo_Input, 0, QtCore.Qt.AlignLeft)
        self.SE_Midi_Tempo_BPM = QtWidgets.QLabel(self.SE_Midi_Tempo)
        self.SE_Midi_Tempo_BPM.setObjectName("SE_Midi_Tempo_BPM")
        self.SE_Midi_Tempo_Layout.addWidget(self.SE_Midi_Tempo_BPM)
        self.verticalLayout.addLayout(self.SE_Midi_Tempo_Layout)
        self.SE_Midi_Info.addWidget(self.SE_Midi_Tempo)
        self.SE_Midi_vLine_1 = QtWidgets.QFrame(self.SE_Midi)
        self.SE_Midi_vLine_1.setFrameShape(QtWidgets.QFrame.VLine)
        self.SE_Midi_vLine_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.SE_Midi_vLine_1.setObjectName("SE_Midi_vLine_1")
        self.SE_Midi_Info.addWidget(self.SE_Midi_vLine_1)
        self.SE_Midi_Length = QtWidgets.QFrame(self.SE_Midi)
        self.SE_Midi_Length.setMaximumSize(QtCore.QSize(222, 16777215))
        self.SE_Midi_Length.setObjectName("SE_Midi_Length")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.SE_Midi_Length)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.SE_Midi_Length_Label = QtWidgets.QLabel(self.SE_Midi_Length)
        self.SE_Midi_Length_Label.setObjectName("SE_Midi_Length_Label")
        self.verticalLayout_8.addWidget(self.SE_Midi_Length_Label)
        self.SE_Midi_Length_Layout = QtWidgets.QHBoxLayout()
        self.SE_Midi_Length_Layout.setObjectName("SE_Midi_Length_Layout")
        self.SE_Midi_Length_Input = QtWidgets.QLineEdit(self.SE_Midi_Length)
        self.SE_Midi_Length_Input.setObjectName("SE_Midi_Length_Input")
        self.SE_Midi_Length_Layout.addWidget(self.SE_Midi_Length_Input)
        self.SE_Midi_Length_Measures = QtWidgets.QRadioButton(self.SE_Midi_Length)
        self.SE_Midi_Length_Measures.setFocusPolicy(QtCore.Qt.TabFocus)
        self.SE_Midi_Length_Measures.setChecked(True)
        self.SE_Midi_Length_Measures.setObjectName("SE_Midi_Length_Measures")
        self.SE_Midi_Length_Layout.addWidget(self.SE_Midi_Length_Measures, 0, QtCore.Qt.AlignHCenter)
        self.SE_Midi_Length_Beats = QtWidgets.QRadioButton(self.SE_Midi_Length)
        self.SE_Midi_Length_Beats.setFocusPolicy(QtCore.Qt.TabFocus)
        self.SE_Midi_Length_Beats.setChecked(False)
        self.SE_Midi_Length_Beats.setObjectName("SE_Midi_Length_Beats")
        self.SE_Midi_Length_Layout.addWidget(self.SE_Midi_Length_Beats, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_8.addLayout(self.SE_Midi_Length_Layout)
        self.SE_Midi_Info.addWidget(self.SE_Midi_Length)
        self.SE_Midi_vLine_2 = QtWidgets.QFrame(self.SE_Midi)
        self.SE_Midi_vLine_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.SE_Midi_vLine_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.SE_Midi_vLine_2.setObjectName("SE_Midi_vLine_2")
        self.SE_Midi_Info.addWidget(self.SE_Midi_vLine_2)
        self.SE_Midi_TimeSignature = QtWidgets.QFrame(self.SE_Midi)
        self.SE_Midi_TimeSignature.setMaximumSize(QtCore.QSize(106, 16777215))
        self.SE_Midi_TimeSignature.setObjectName("SE_Midi_TimeSignature")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.SE_Midi_TimeSignature)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.SE_Midi_TimeSignature_Label = QtWidgets.QLabel(self.SE_Midi_TimeSignature)
        self.SE_Midi_TimeSignature_Label.setObjectName("SE_Midi_TimeSignature_Label")
        self.verticalLayout_6.addWidget(self.SE_Midi_TimeSignature_Label, 0, QtCore.Qt.AlignTop)
        self.SE_Midi_TimeSignature_Layout = QtWidgets.QHBoxLayout()
        self.SE_Midi_TimeSignature_Layout.setObjectName("SE_Midi_TimeSignature_Layout")
        self.SE_Midi_TimeSignature_4 = QtWidgets.QRadioButton(self.SE_Midi_TimeSignature)
        self.SE_Midi_TimeSignature_4.setMouseTracking(True)
        self.SE_Midi_TimeSignature_4.setFocusPolicy(QtCore.Qt.TabFocus)
        self.SE_Midi_TimeSignature_4.setChecked(True)
        self.SE_Midi_TimeSignature_4.setObjectName("SE_Midi_TimeSignature_4")
        self.SE_Midi_TimeSignature_Layout.addWidget(self.SE_Midi_TimeSignature_4)
        self.SE_Midi_TimeSignature_3 = QtWidgets.QRadioButton(self.SE_Midi_TimeSignature)
        self.SE_Midi_TimeSignature_3.setFocusPolicy(QtCore.Qt.TabFocus)
        self.SE_Midi_TimeSignature_3.setObjectName("SE_Midi_TimeSignature_3")
        self.SE_Midi_TimeSignature_Layout.addWidget(self.SE_Midi_TimeSignature_3)
        self.verticalLayout_6.addLayout(self.SE_Midi_TimeSignature_Layout)
        self.SE_Midi_Info.addWidget(self.SE_Midi_TimeSignature)
        self.verticalLayout_4.addLayout(self.SE_Midi_Info)
        self.SE_MidiAndText.addWidget(self.SE_Midi)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.SE_MidiAndText.addItem(spacerItem1)
        self.SE_ChangeSongText = QtWidgets.QGroupBox(self.SongEditor)
        self.SE_ChangeSongText.setEnabled(True)
        self.SE_ChangeSongText.setMaximumSize(QtCore.QSize(16777215, 181))
        self.SE_ChangeSongText.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.SE_ChangeSongText.setCheckable(False)
        self.SE_ChangeSongText.setChecked(False)
        self.SE_ChangeSongText.setObjectName("SE_ChangeSongText")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.SE_ChangeSongText)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.SE_ChangeSongText_NameAndGenre = QtWidgets.QHBoxLayout()
        self.SE_ChangeSongText_NameAndGenre.setObjectName("SE_ChangeSongText_NameAndGenre")
        self.SE_ChangeSongText_Name = QtWidgets.QVBoxLayout()
        self.SE_ChangeSongText_Name.setObjectName("SE_ChangeSongText_Name")
        self.SE_ChangeSongText_Name_Label = QtWidgets.QLabel(self.SE_ChangeSongText)
        self.SE_ChangeSongText_Name_Label.setMaximumSize(QtCore.QSize(16777215, 13))
        self.SE_ChangeSongText_Name_Label.setObjectName("SE_ChangeSongText_Name_Label")
        self.SE_ChangeSongText_Name.addWidget(self.SE_ChangeSongText_Name_Label)
        self.SE_ChangeSongText_Name_Input = QtWidgets.QLineEdit(self.SE_ChangeSongText)
        self.SE_ChangeSongText_Name_Input.setMaximumSize(QtCore.QSize(16777215, 20))
        self.SE_ChangeSongText_Name_Input.setText("")
        self.SE_ChangeSongText_Name_Input.setObjectName("SE_ChangeSongText_Name_Input")
        self.SE_ChangeSongText_Name.addWidget(self.SE_ChangeSongText_Name_Input)
        self.SE_ChangeSongText_NameAndGenre.addLayout(self.SE_ChangeSongText_Name)
        self.SE_ChangeSongText_vLine = QtWidgets.QFrame(self.SE_ChangeSongText)
        self.SE_ChangeSongText_vLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.SE_ChangeSongText_vLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.SE_ChangeSongText_vLine.setObjectName("SE_ChangeSongText_vLine")
        self.SE_ChangeSongText_NameAndGenre.addWidget(self.SE_ChangeSongText_vLine)
        self.SE_ChangeSongText_Genre = QtWidgets.QVBoxLayout()
        self.SE_ChangeSongText_Genre.setObjectName("SE_ChangeSongText_Genre")
        self.SE_ChangeSongText_Genre_Label = QtWidgets.QLabel(self.SE_ChangeSongText)
        self.SE_ChangeSongText_Genre_Label.setMaximumSize(QtCore.QSize(16777215, 13))
        self.SE_ChangeSongText_Genre_Label.setObjectName("SE_ChangeSongText_Genre_Label")
        self.SE_ChangeSongText_Genre.addWidget(self.SE_ChangeSongText_Genre_Label)
        self.SE_ChangeSongText_Genre_Input = QtWidgets.QLineEdit(self.SE_ChangeSongText)
        self.SE_ChangeSongText_Genre_Input.setText("")
        self.SE_ChangeSongText_Genre_Input.setObjectName("SE_ChangeSongText_Genre_Input")
        self.SE_ChangeSongText_Genre.addWidget(self.SE_ChangeSongText_Genre_Input)
        self.SE_ChangeSongText_NameAndGenre.addLayout(self.SE_ChangeSongText_Genre)
        self.verticalLayout_5.addLayout(self.SE_ChangeSongText_NameAndGenre)
        self.SE_ChangeSongText_hLine = QtWidgets.QFrame(self.SE_ChangeSongText)
        self.SE_ChangeSongText_hLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.SE_ChangeSongText_hLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.SE_ChangeSongText_hLine.setObjectName("SE_ChangeSongText_hLine")
        self.verticalLayout_5.addWidget(self.SE_ChangeSongText_hLine)
        self.SE_ChangeSongText_Desc_Label = QtWidgets.QLabel(self.SE_ChangeSongText)
        self.SE_ChangeSongText_Desc_Label.setObjectName("SE_ChangeSongText_Desc_Label")
        self.verticalLayout_5.addWidget(self.SE_ChangeSongText_Desc_Label)
        self.SE_ChangeSongText_Desc_Input = QtWidgets.QPlainTextEdit(self.SE_ChangeSongText)
        self.SE_ChangeSongText_Desc_Input.setMinimumSize(QtCore.QSize(0, 71))
        self.SE_ChangeSongText_Desc_Input.setMaximumSize(QtCore.QSize(16777215, 71))
        self.SE_ChangeSongText_Desc_Input.setAcceptDrops(False)
        self.SE_ChangeSongText_Desc_Input.setPlainText("")
        self.SE_ChangeSongText_Desc_Input.setObjectName("SE_ChangeSongText_Desc_Input")
        self.verticalLayout_5.addWidget(self.SE_ChangeSongText_Desc_Input)
        self.SE_MidiAndText.addWidget(self.SE_ChangeSongText)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.SE_MidiAndText.addItem(spacerItem2)
        self.SE_Patch = QtWidgets.QPushButton(self.SongEditor)
        self.SE_Patch.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(20)
        self.SE_Patch.setFont(font)
        self.SE_Patch.setObjectName("SE_Patch")
        self.SE_MidiAndText.addWidget(self.SE_Patch)
        self.SE_MainLayout.addLayout(self.SE_MidiAndText)
        self.SE_SongToChangeBox = QtWidgets.QGroupBox(self.SongEditor)
        self.SE_SongToChangeBox.setMinimumSize(QtCore.QSize(0, 0))
        self.SE_SongToChangeBox.setObjectName("SE_SongToChangeBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.SE_SongToChangeBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SE_SongToChange = QtWidgets.QListWidget(self.SE_SongToChangeBox)
        self.SE_SongToChange.setObjectName("SE_SongToChange")
        self.verticalLayout_3.addWidget(self.SE_SongToChange)
        self.SE_MainLayout.addWidget(self.SE_SongToChangeBox)
        self.verticalLayout_2.addLayout(self.SE_MainLayout)
        self.MainWidget.addWidget(self.SongEditor)
        self.StyleEditor = QtWidgets.QWidget()
        self.StyleEditor.setObjectName("StyleEditor")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.StyleEditor)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.SE_Title_2 = QtWidgets.QLabel(self.StyleEditor)
        self.SE_Title_2.setMaximumSize(QtCore.QSize(16777215, 44))
        font = QtGui.QFont()
        font.setFamily("Continuum Medium")
        font.setPointSize(26)
        self.SE_Title_2.setFont(font)
        self.SE_Title_2.setObjectName("SE_Title_2")
        self.verticalLayout_33.addWidget(self.SE_Title_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.SE_Midi_2 = QtWidgets.QGroupBox(self.StyleEditor)
        self.SE_Midi_2.setMaximumSize(QtCore.QSize(16777215, 200))
        self.SE_Midi_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.SE_Midi_2.setCheckable(False)
        self.SE_Midi_2.setObjectName("SE_Midi_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.SE_Midi_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.StE_Part_Melody = QtWidgets.QHBoxLayout()
        self.StE_Part_Melody.setObjectName("StE_Part_Melody")
        self.StE_Part_Melody_Label = QtWidgets.QLabel(self.SE_Midi_2)
        self.StE_Part_Melody_Label.setMaximumSize(QtCore.QSize(47, 16777215))
        self.StE_Part_Melody_Label.setObjectName("StE_Part_Melody_Label")
        self.StE_Part_Melody.addWidget(self.StE_Part_Melody_Label)
        self.StE_Part_Melody_Instrument = QtWidgets.QLabel(self.SE_Midi_2)
        self.StE_Part_Melody_Instrument.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.StE_Part_Melody_Instrument.setFont(font)
        self.StE_Part_Melody_Instrument.setAcceptDrops(True)
        self.StE_Part_Melody_Instrument.setStyleSheet("padding: 1px;\n"
"border: 1px solid;\n"
"border-color: #1e1e1e;\n"
"background-color: #242424;")
        self.StE_Part_Melody_Instrument.setObjectName("StE_Part_Melody_Instrument")
        self.StE_Part_Melody.addWidget(self.StE_Part_Melody_Instrument)
        self.StE_Part_Melody_Button = QtWidgets.QPushButton(self.SE_Midi_2)
        self.StE_Part_Melody_Button.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        self.StE_Part_Melody_Button.setFont(font)
        self.StE_Part_Melody_Button.setObjectName("StE_Part_Melody_Button")
        self.StE_Part_Melody.addWidget(self.StE_Part_Melody_Button)
        self.verticalLayout_7.addLayout(self.StE_Part_Melody)
        self.StE_Part_Melody_2 = QtWidgets.QHBoxLayout()
        self.StE_Part_Melody_2.setObjectName("StE_Part_Melody_2")
        self.StE_Part_Melody_Label_2 = QtWidgets.QLabel(self.SE_Midi_2)
        self.StE_Part_Melody_Label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.StE_Part_Melody_Label_2.setMaximumSize(QtCore.QSize(47, 16777215))
        self.StE_Part_Melody_Label_2.setObjectName("StE_Part_Melody_Label_2")
        self.StE_Part_Melody_2.addWidget(self.StE_Part_Melody_Label_2)
        self.StE_Part_Melody_Instrument_2 = QtWidgets.QLabel(self.SE_Midi_2)
        self.StE_Part_Melody_Instrument_2.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.StE_Part_Melody_Instrument_2.setFont(font)
        self.StE_Part_Melody_Instrument_2.setAcceptDrops(True)
        self.StE_Part_Melody_Instrument_2.setStyleSheet("padding: 1px;\n"
"border: 1px solid;\n"
"border-color: #1e1e1e;\n"
"background-color: #242424;")
        self.StE_Part_Melody_Instrument_2.setObjectName("StE_Part_Melody_Instrument_2")
        self.StE_Part_Melody_2.addWidget(self.StE_Part_Melody_Instrument_2)
        self.StE_Part_Melody_Button_2 = QtWidgets.QPushButton(self.SE_Midi_2)
        self.StE_Part_Melody_Button_2.setMinimumSize(QtCore.QSize(0, 0))
        self.StE_Part_Melody_Button_2.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        self.StE_Part_Melody_Button_2.setFont(font)
        self.StE_Part_Melody_Button_2.setObjectName("StE_Part_Melody_Button_2")
        self.StE_Part_Melody_2.addWidget(self.StE_Part_Melody_Button_2)
        self.verticalLayout_7.addLayout(self.StE_Part_Melody_2)
        self.StE_Part_Melody_4 = QtWidgets.QHBoxLayout()
        self.StE_Part_Melody_4.setObjectName("StE_Part_Melody_4")
        self.StE_Part_Melody_Label_4 = QtWidgets.QLabel(self.SE_Midi_2)
        self.StE_Part_Melody_Label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.StE_Part_Melody_Label_4.setMaximumSize(QtCore.QSize(47, 16777215))
        self.StE_Part_Melody_Label_4.setObjectName("StE_Part_Melody_Label_4")
        self.StE_Part_Melody_4.addWidget(self.StE_Part_Melody_Label_4)
        self.StE_Part_Melody_Instrument_4 = QtWidgets.QLabel(self.SE_Midi_2)
        self.StE_Part_Melody_Instrument_4.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.StE_Part_Melody_Instrument_4.setFont(font)
        self.StE_Part_Melody_Instrument_4.setAcceptDrops(True)
        self.StE_Part_Melody_Instrument_4.setStyleSheet("padding: 1px;\n"
"border: 1px solid;\n"
"border-color: #1e1e1e;\n"
"background-color: #242424;")
        self.StE_Part_Melody_Instrument_4.setObjectName("StE_Part_Melody_Instrument_4")
        self.StE_Part_Melody_4.addWidget(self.StE_Part_Melody_Instrument_4)
        self.StE_Part_Melody_Button_4 = QtWidgets.QPushButton(self.SE_Midi_2)
        self.StE_Part_Melody_Button_4.setMinimumSize(QtCore.QSize(0, 0))
        self.StE_Part_Melody_Button_4.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        self.StE_Part_Melody_Button_4.setFont(font)
        self.StE_Part_Melody_Button_4.setObjectName("StE_Part_Melody_Button_4")
        self.StE_Part_Melody_4.addWidget(self.StE_Part_Melody_Button_4)
        self.verticalLayout_7.addLayout(self.StE_Part_Melody_4)
        self.StE_Part_Melody_3 = QtWidgets.QHBoxLayout()
        self.StE_Part_Melody_3.setObjectName("StE_Part_Melody_3")
        self.StE_Part_Melody_Label_3 = QtWidgets.QLabel(self.SE_Midi_2)
        self.StE_Part_Melody_Label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.StE_Part_Melody_Label_3.setMaximumSize(QtCore.QSize(47, 16777215))
        self.StE_Part_Melody_Label_3.setObjectName("StE_Part_Melody_Label_3")
        self.StE_Part_Melody_3.addWidget(self.StE_Part_Melody_Label_3)
        self.StE_Part_Melody_Instrument_3 = QtWidgets.QLabel(self.SE_Midi_2)
        self.StE_Part_Melody_Instrument_3.setMaximumSize(QtCore.QSize(16777215, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.StE_Part_Melody_Instrument_3.setFont(font)
        self.StE_Part_Melody_Instrument_3.setAcceptDrops(True)
        self.StE_Part_Melody_Instrument_3.setStyleSheet("padding: 1px;\n"
"border: 1px solid;\n"
"border-color: #1e1e1e;\n"
"background-color: #242424;")
        self.StE_Part_Melody_Instrument_3.setObjectName("StE_Part_Melody_Instrument_3")
        self.StE_Part_Melody_3.addWidget(self.StE_Part_Melody_Instrument_3)
        self.StE_Part_Melody_Button_3 = QtWidgets.QPushButton(self.SE_Midi_2)
        self.StE_Part_Melody_Button_3.setMinimumSize(QtCore.QSize(0, 0))
        self.StE_Part_Melody_Button_3.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        self.StE_Part_Melody_Button_3.setFont(font)
        self.StE_Part_Melody_Button_3.setObjectName("StE_Part_Melody_Button_3")
        self.StE_Part_Melody_3.addWidget(self.StE_Part_Melody_Button_3)
        self.verticalLayout_7.addLayout(self.StE_Part_Melody_3)
        self.verticalLayout_17.addWidget(self.SE_Midi_2)
        self.SE_ChangeSongText_2 = QtWidgets.QGroupBox(self.StyleEditor)
        self.SE_ChangeSongText_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.SE_ChangeSongText_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.SE_ChangeSongText_2.setCheckable(False)
        self.SE_ChangeSongText_2.setChecked(False)
        self.SE_ChangeSongText_2.setObjectName("SE_ChangeSongText_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.SE_ChangeSongText_2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.SE_ChangeSongText_Name_Text_2 = QtWidgets.QLineEdit(self.SE_ChangeSongText_2)
        self.SE_ChangeSongText_Name_Text_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.SE_ChangeSongText_Name_Text_2.setObjectName("SE_ChangeSongText_Name_Text_2")
        self.verticalLayout_12.addWidget(self.SE_ChangeSongText_Name_Text_2)
        self.verticalLayout_17.addWidget(self.SE_ChangeSongText_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_17)
        self.SE_SongToChangeBox_5 = QtWidgets.QGroupBox(self.StyleEditor)
        self.SE_SongToChangeBox_5.setMinimumSize(QtCore.QSize(0, 0))
        self.SE_SongToChangeBox_5.setMaximumSize(QtCore.QSize(175, 16777215))
        self.SE_SongToChangeBox_5.setObjectName("SE_SongToChangeBox_5")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.SE_SongToChangeBox_5)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.listWidget_6 = QtWidgets.QListWidget(self.SE_SongToChangeBox_5)
        self.listWidget_6.setObjectName("listWidget_6")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_6.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_6.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_6.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_6.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_6.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_6.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_6.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_6.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_6.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_6.addItem(item)
        self.verticalLayout_32.addWidget(self.listWidget_6)
        self.horizontalLayout_7.addWidget(self.SE_SongToChangeBox_5)
        self.SE_SongToChangeBox_2 = QtWidgets.QGroupBox(self.StyleEditor)
        self.SE_SongToChangeBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.SE_SongToChangeBox_2.setMaximumSize(QtCore.QSize(175, 16777215))
        self.SE_SongToChangeBox_2.setObjectName("SE_SongToChangeBox_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.SE_SongToChangeBox_2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.listWidget_2 = QtWidgets.QListWidget(self.SE_SongToChangeBox_2)
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.verticalLayout_13.addWidget(self.listWidget_2)
        self.horizontalLayout_7.addWidget(self.SE_SongToChangeBox_2)
        self.verticalLayout_33.addLayout(self.horizontalLayout_7)
        self.SE_Patch_2 = QtWidgets.QPushButton(self.StyleEditor)
        self.SE_Patch_2.setObjectName("SE_Patch_2")
        self.verticalLayout_33.addWidget(self.SE_Patch_2)
        self.MainWidget.addWidget(self.StyleEditor)
        self.horizontalLayout.addWidget(self.MainWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 698, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.MB_CheckForUpdates = QtWidgets.QMenu(self.menubar)
        self.MB_CheckForUpdates.setObjectName("MB_CheckForUpdates")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.MB_LoadFile = QtWidgets.QAction(MainWindow)
        self.MB_LoadFile.setObjectName("MB_LoadFile")
        self.MB_LoadFolder = QtWidgets.QAction(MainWindow)
        self.MB_LoadFolder.setObjectName("MB_LoadFolder")
        self.MB_Dolphin = QtWidgets.QAction(MainWindow)
        self.MB_Dolphin.setObjectName("MB_Dolphin")
        self.MB_DolphinMenu = QtWidgets.QAction(MainWindow)
        self.MB_DolphinMenu.setObjectName("MB_DolphinMenu")
        self.MB_CheckForUpdates_2 = QtWidgets.QAction(MainWindow)
        self.MB_CheckForUpdates_2.setObjectName("MB_CheckForUpdates_2")
        self.menuFile.addAction(self.MB_LoadFile)
        self.menuFile.addAction(self.MB_LoadFolder)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.MB_Dolphin)
        self.menuFile.addAction(self.MB_DolphinMenu)
        self.menuFile.addSeparator()
        self.MB_CheckForUpdates.addAction(self.MB_CheckForUpdates_2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.MB_CheckForUpdates.menuAction())

        self.retranslateUi(MainWindow)
        self.MainWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wii Music Editor Plus"))
        self.MP_Title.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/images/images/Title.png\"/></p></body></html>"))
        self.MP_LoadedFile_Label.setText(_translate("MainWindow", "Currently Loaded File:"))
        self.MP_LoadedFile_Path.setText(_translate("MainWindow", "No File Loaded"))
        self.MP_SongEditor_Button.setText(_translate("MainWindow", "Song Editor"))
        self.MP_StyleEditor_Button.setText(_translate("MainWindow", "Style Editor"))
        self.SE_Title.setText(_translate("MainWindow", "Song Editor"))
        self.SE_Back_Button.setText(_translate("MainWindow", " Back"))
        self.SE_Midi.setTitle(_translate("MainWindow", "Replace Song"))
        self.SE_Midi_File_Label.setText(_translate("MainWindow", "Load a Midi-Type file"))
        self.SE_Midi_File_Button.setText(_translate("MainWindow", "Browse"))
        self.SE_Midi_Tempo_Label.setText(_translate("MainWindow", "Tempo:"))
        self.SE_Midi_Tempo_BPM.setText(_translate("MainWindow", "BPM"))
        self.SE_Midi_Length_Label.setText(_translate("MainWindow", "Length:"))
        self.SE_Midi_Length_Measures.setText(_translate("MainWindow", "Measures"))
        self.SE_Midi_Length_Beats.setText(_translate("MainWindow", "Beats"))
        self.SE_Midi_TimeSignature_Label.setText(_translate("MainWindow", "Time Signature:"))
        self.SE_Midi_TimeSignature_4.setText(_translate("MainWindow", "4/4"))
        self.SE_Midi_TimeSignature_3.setText(_translate("MainWindow", "3/4"))
        self.SE_ChangeSongText.setTitle(_translate("MainWindow", "Change Song Text"))
        self.SE_ChangeSongText_Name_Label.setText(_translate("MainWindow", "Name:"))
        self.SE_ChangeSongText_Genre_Label.setText(_translate("MainWindow", "Genre:"))
        self.SE_ChangeSongText_Desc_Label.setText(_translate("MainWindow", "Description:"))
        self.SE_Patch.setText(_translate("MainWindow", "Patch!"))
        self.SE_SongToChangeBox.setTitle(_translate("MainWindow", "Song to change"))
        self.SE_Title_2.setText(_translate("MainWindow", "Style Editor"))
        self.SE_Midi_2.setTitle(_translate("MainWindow", "Part Selector"))
        self.StE_Part_Melody_Label.setText(_translate("MainWindow", "Melody:"))
        self.StE_Part_Melody_Instrument.setText(_translate("MainWindow", "The Cheese Grater"))
        self.StE_Part_Melody_Button.setText(_translate("MainWindow", "Change"))
        self.StE_Part_Melody_Label_2.setText(_translate("MainWindow", "Harmony:"))
        self.StE_Part_Melody_Instrument_2.setText(_translate("MainWindow", "12 Pounds of Avacados"))
        self.StE_Part_Melody_Button_2.setText(_translate("MainWindow", "Change"))
        self.StE_Part_Melody_Label_4.setText(_translate("MainWindow", "Chords:"))
        self.StE_Part_Melody_Instrument_4.setText(_translate("MainWindow", "Dave Tirelessly Yelling"))
        self.StE_Part_Melody_Button_4.setText(_translate("MainWindow", "Change"))
        self.StE_Part_Melody_Label_3.setText(_translate("MainWindow", "Bass:"))
        self.StE_Part_Melody_Instrument_3.setText(_translate("MainWindow", "Guitar"))
        self.StE_Part_Melody_Button_3.setText(_translate("MainWindow", "Change"))
        self.SE_ChangeSongText_2.setTitle(_translate("MainWindow", "Change Style Name"))
        self.SE_ChangeSongText_Name_Text_2.setText(_translate("MainWindow", "Funky Man Style"))
        self.SE_SongToChangeBox_5.setTitle(_translate("MainWindow", "Select Instrument (Melody)"))
        __sortingEnabled = self.listWidget_6.isSortingEnabled()
        self.listWidget_6.setSortingEnabled(False)
        item = self.listWidget_6.item(0)
        item.setText(_translate("MainWindow", "Hi"))
        item = self.listWidget_6.item(1)
        item.setText(_translate("MainWindow", "These"))
        item = self.listWidget_6.item(2)
        item.setText(_translate("MainWindow", "Are Songs"))
        item = self.listWidget_6.item(3)
        item.setText(_translate("MainWindow", "Yep They Sure Are"))
        item = self.listWidget_6.item(4)
        item.setText(_translate("MainWindow", "This one even has a :0"))
        item = self.listWidget_6.item(5)
        item.setText(_translate("MainWindow", "How cool is that"))
        item = self.listWidget_6.item(6)
        item.setText(_translate("MainWindow", "Dont forget to"))
        item = self.listWidget_6.item(7)
        item.setText(_translate("MainWindow", "Like and Subscribe"))
        item = self.listWidget_6.item(8)
        item.setText(_translate("MainWindow", "For More Epic"))
        item = self.listWidget_6.item(9)
        item.setText(_translate("MainWindow", "UI Pictures!"))
        self.listWidget_6.setSortingEnabled(__sortingEnabled)
        self.SE_SongToChangeBox_2.setTitle(_translate("MainWindow", "Style to change"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", "Hi"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("MainWindow", "These"))
        item = self.listWidget_2.item(2)
        item.setText(_translate("MainWindow", "Are Songs"))
        item = self.listWidget_2.item(3)
        item.setText(_translate("MainWindow", "Yep They Sure Are"))
        item = self.listWidget_2.item(4)
        item.setText(_translate("MainWindow", "This one even has a :0"))
        item = self.listWidget_2.item(5)
        item.setText(_translate("MainWindow", "How cool is that"))
        item = self.listWidget_2.item(6)
        item.setText(_translate("MainWindow", "Dont forget to"))
        item = self.listWidget_2.item(7)
        item.setText(_translate("MainWindow", "Like and Subscribe"))
        item = self.listWidget_2.item(8)
        item.setText(_translate("MainWindow", "For More Epic"))
        item = self.listWidget_2.item(9)
        item.setText(_translate("MainWindow", "UI Pictures!"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.SE_Patch_2.setText(_translate("MainWindow", "Patch!"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.MB_CheckForUpdates.setTitle(_translate("MainWindow", "Settings"))
        self.MB_LoadFile.setText(_translate("MainWindow", "Load Wii Music File"))
        self.MB_LoadFolder.setText(_translate("MainWindow", "Load Wii Music Folder"))
        self.MB_Dolphin.setText(_translate("MainWindow", "Run Dolphin"))
        self.MB_Dolphin.setShortcut(_translate("MainWindow", "F5"))
        self.MB_DolphinMenu.setText(_translate("MainWindow", "Run Dolphin (Menu)"))
        self.MB_DolphinMenu.setToolTip(_translate("MainWindow", "Run Dolphin (Menu)"))
        self.MB_DolphinMenu.setShortcut(_translate("MainWindow", "F6"))
        self.MB_CheckForUpdates_2.setText(_translate("MainWindow", "Check for Updates"))
import resources_rc
