[package]
name = "wm_core"
version = "0.1.0"
edition = "2024"

[dependencies]
binrw = { workspace = true }
midly = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
brsar = { path = "../brsar" }
carc = { path = "../carc" }
iso = { path = "../iso" }
sha1 = "0.10"
zip = { version = "2", default-features = false, features = ["deflate", "time"] }
sysinfo = "0.33"
tempfile = "3"

[lints]
workspace = true
