name: Build App
on:
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.12"

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with: 
        python-version: ${{ env.PYTHON_VERSION }}
        architecture: 'x64'

    - name: Install Requirements
      run: poetry install

    - name: Build
      run: poetry run build

    - name: Package for MacOS
      if: startsWith(matrix.os, 'macOS')
      run: |
        brew install platypus
        platypus -y -B -R -i 'include/all/icon/icon.icns'  -a 'WiiMusicEditorPlus'  -o 'None'  -p '/bin/sh' -f 'dist/WiiMusicEditorPlus' macscript.sh dist/WiiMusicEditorPlus.app
        rm -r dist/WiiMusicEditorPlus

    - name: Upload Build
      uses: actions/upload-artifact@v3
      with:
        name: WiiMusicEditorPlus-${{ matrix.os }}
        path: dist
