name: Build App
on: 
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        description: Platform
        options:
        - All
        - Windows
        - Linux
        - MacOS
jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    if:  ${{ inputs.platform }} == 'All' || ${{ inputs.platform }} == 'Windows'
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with: 
        python-version: '3.9'
        architecture: 'x64'
    - name: Build It
      run: |
        pip install -r requirements.txt
        pyinstaller -w --noconfirm --add-data crossplatformhelpers/Windows/Helper;Helper --icon icon/icon.ico --add-data translations/translations;translations WiiMusicEditorPlus.py
      shell: cmd
    - name: Upload Windows Build
      uses: actions/upload-artifact@v3
      with:
        name: WiiMusicEditorPlus-Windows
        path: dist