name: Build App
on: 
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Setup Python
      uses: actions/setup-python@v4
      with: 
        python-version: '3.9'
        architecture: 'x64'
    - name: Build It
      run: |
        pip install -r requirements.txt
        build-windows.bat
    - name: Upload Windows Build
      uses: actions/upload-artifact@v3
      with:
        name: editor-windows
        path: dist/WiiMusicEditorPlus-Windows.zip