name: Continuous Integration

on:
  push:
    branches:
      - main
      - dev-rust
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install system dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -y --no-install-recommends \
            libfontconfig-dev \
            libgtk-3-dev \
            pkg-config \
            libxkbcommon-dev \
            libegl-dev \
            libwayland-dev \
            libx11-dev
      - run: cargo check --all-targets

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install system dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -y --no-install-recommends \
            libfontconfig-dev \
            libgtk-3-dev \
            pkg-config \
            libxkbcommon-dev \
            libegl-dev \
            libwayland-dev \
            libx11-dev
      - run: cargo test

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Install system dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -y --no-install-recommends \
            libfontconfig-dev \
            libgtk-3-dev \
            pkg-config \
            libxkbcommon-dev \
            libegl-dev \
            libwayland-dev \
            libx11-dev
      - run: cargo clippy -- -Dwarnings
